### ISSUE TITLE
NullPointerException when executing /mt recipes

### ISSUE THREAD

**Issue by iarspider** [stanhebben/MineTweaker3#106]
Error:
```
[19/11/2014 12:11:51 PM] [Server thread/ERROR]: Couldn't process command: 'mt recipes'
[19/11/2014 12:11:51 PM] java.lang.NullPointerException
[19/11/2014 12:11:51 PM] 	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217) ~[add.class:?]
[19/11/2014 12:11:51 PM] 	at minetweaker.mc1710.item.MCItemStack.toString(MCItemStack.java:348) ~[MCItemStack.class:?]
[19/11/2014 12:11:51 PM] 	at java.lang.String.valueOf(Unknown Source) ~[?:1.7.0_67]
[19/11/2014 12:11:51 PM] 	at java.lang.StringBuilder.append(Unknown Source) ~[?:1.7.0_67]
[19/11/2014 12:11:51 PM] 	at minetweaker.api.recipes.ShapedRecipe.toCommandString(ShapedRecipe.java:224) ~[ShapedRecipe.class:?]
[19/11/2014 12:11:51 PM] 	at minetweaker.MineTweakerImplementationAPI$6.execute(MineTweakerImplementationAPI.java:203) ~[MineTweakerImplementationAPI$6.class:?]
[19/11/2014 12:11:51 PM] 	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610) ~[MineTweakerImplementationAPI$19.class:?]
[19/11/2014 12:11:51 PM] 	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124) ~[MCServer$MCCommand.class:?]
[19/11/2014 12:11:51 PM] 	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
[19/11/2014 12:11:51 PM] 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
[19/11/2014 12:11:51 PM] 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
[19/11/2014 12:11:51 PM] 	at com.mumfrey.liteloader.client.CallbackProxyClient.handleServerChatPacket(CallbackProxyClient.java:79) [CallbackProxyClient.class:1.7.10_02]
[19/11/2014 12:11:51 PM] 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile) [ir.class:?]
[19/11/2014 12:11:51 PM] 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[19/11/2014 12:11:51 PM] 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
[19/11/2014 12:11:51 PM] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
[19/11/2014 12:11:51 PM] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
[19/11/2014 12:11:51 PM] 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
[19/11/2014 12:11:51 PM] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
[19/11/2014 12:11:51 PM] 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
```

Could you please add a code to print the name/class/anything of the item that caused that NPE so that I could ~~kick the modder~~ kindly ask the modder to fix that nonsence?

**Comment by jaredlll08** [comment]
Please can we have more information on this.

**Comment by iarspider** [comment]
This happened too long ago, I don't have that pack (DIY kind of a pack) any more.

**Comment by jaredlll08** [comment]
Ah, ok well I worked on the command a bit, so it should have fixed this :)
