### ISSUE TITLE
/mt recipes hand Error

### ISSUE THREAD

**Issue by SirWilli** [stanhebben/MineTweaker3#119]
Version: MineTweaker 3.0.9C for Minecraft 1.7.10

```
[00:13:16] [Server thread/ERROR]: Couldn't process command: 'mt recipes hand'
java.lang.NullPointerException
	at minetweaker.mc1710.item.MCItemStack.matches(MCItemStack.java:250) ~[MCItemStack.class:?]
	at minetweaker.mc1710.recipes.MCRecipeManager.getRecipesFor(MCRecipeManager.java:63) ~[MCRecipeManager.class:?]
	at minetweaker.MineTweakerImplementationAPI$6.execute(MineTweakerImplementationAPI.java:212) ~[MineTweakerImplementationAPI$6.class:?]
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610) ~[MineTweakerImplementationAPI$19.class:?]
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124) ~[MCServer$MCCommand.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[00:13:16] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command
```

**Comment by MrPotatoGaming** [comment]
It happens when using the command on a server. Whenever I'm setting up scripts - I have to do it all in single player than copy it over to the multiplayer server. Its not really a large issue, just a bit peculiar. I think it also only happens for things in the Forge Dictionary - but I haven't done that command in a while.
