### ISSUE TITLE
Using /minetweaker hand on dedicated server

### ISSUE THREAD

**Issue by Voidi** [stanhebben/MineTweaker3#146]
works most of the time, and throws everytime an error
``[16:54:42] [Server thread/ERROR]: Couldn't process command: 'minetweaker hand'
java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at sun.awt.HeadlessToolkit.getSystemClipboard(HeadlessToolkit.java:307) ~[?:1.7.0_55]
	at minetweaker.MineTweakerImplementationAPI.copyToClipboard(MineTweakerImplementationAPI.java:648) ~[MineTweakerImplementationAPI.class:?]
	at minetweaker.MineTweakerImplementationAPI.access$1100(MineTweakerImplementationAPI.java:55) ~[MineTweakerImplementationAPI.class:?]
	at minetweaker.MineTweakerImplementationAPI$8.execute(MineTweakerImplementationAPI.java:265) ~[MineTweakerImplementationAPI$8.class:?]
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610) ~[MineTweakerImplementationAPI$19.class:?]
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124) ~[MCServer$MCCommand.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]``

**Comment by jaredlll08** [comment]
This has been fixed.

**Comment by HanPrower** [comment]
@jaredlll08: When? Because MineTweaker3-1.7.10-3.0.10B still does it.

**Comment by jaredlll08** [comment]
Take a look at craft tweaker,  I'm 75% sure that I released it in there,
http://minecraft.curseforge.com/projects/crafttweaker-customized-mineweaker3

**Comment by Tsyklop** [comment]
@jaredlll08 this is not fixed.

**Comment by PantACRO4life** [comment]
not fixed

**Comment by jaredlll08** [comment]
So you are saying, in the latest version of crafttweaker, this is not fixed?
