### ISSUE TITLE
loot removal doesn't work

### ISSUE THREAD

**Issue by Voidi** [stanhebben/MineTweaker3#147]
tested with the example from the wiki:

``vanilla.loot.addChestLoot("dungeonChest", <minecraft:diamond>.weight(100));``

``ERROR: Error executing loot_removal.zs: null
java.lang.NullPointerException
	at minetweaker.mc1710.util.MineTweakerHacks.getPrivateObject(MineTweakerHacks.java:250)
	at minetweaker.mc1710.vanilla.MCLootRegistry$RemoveLootAction.apply(MCLootRegistry.java:160)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:65)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:173)
	at minetweaker.mc1710.vanilla.MCLootRegistry.removeChestLoot(MCLootRegistry.java:53)
	at Loot_removal.__script__(loot_removal.zs:26)
	at __ZenMain__.run(loot_removal.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)``

**Comment by jaredlll08** [comment]
Just tested this in the latest version, it works fine:
INFO: Adding chest loot Diamond to loot class dungeonChest
