### ISSUE TITLE
Buildcraft refinery add recipe problem

### ISSUE THREAD

**Issue by Hazado** [stanhebben/MineTweaker3#159]
The second liquid is required currently. Its set as optional in the code, but its not working correctly.
Attempted the line below and it always errors.
Refinery.addRecipe(<liquid:fuel>, 120, 1, <liquid:oilgc>);

This works though.
Refinery.addRecipe(<liquid:fuel>, 120, 1, <liquid:oilgc>, <liquid:oilgc>);

Error in Minetweaker.log
INFO: Adding refinery recipe for minetweaker.mc1710.liquid.MCLiquidStack@4fb2a7b
ERROR: Error executing Buildcraft.zs: null
java.lang.NullPointerException
	at buildcraft.compat.minetweaker.Refinery$AddRecipeAction.apply(Refinery.java:72)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:65)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:173)
	at buildcraft.compat.minetweaker.Refinery.addRecipe(Refinery.java:35)
	at Buildcraft.__script__(Buildcraft.zs:25)
	at __ZenMain__.run(Buildcraft.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by jaredlll08** [comment]
This is a buildcraft issue, and we no longer add support for buildcraft

**Comment by Yulife** [comment]
You need to report this on them BC Compat repo :)

**Comment by Voidi** [comment]
I already made an issue for this bug https://github.com/BuildCraft/BuildcraftCompat/issues/54

PS: maybe i should fix this in a PR.
