### ISSUE TITLE
Rcon connection does not have any right

### ISSUE THREAD

**Issue by Pyeroh** [stanhebben/MineTweaker3#166]
When I type any command, it says I don't have the permission to do that, and for some commands, I get an error like this

```
[19:50:19] [RCON Client #2/ERROR]: Couldn't process command: 'help'
java.lang.NullPointerException
	at minetweaker.mc1710.server.MCServer.isOp(MCServer.java:61) ~[MCServer.class:?]
	at minetweaker.MineTweakerImplementationAPI$20.canExecute(MineTweakerImplementationAPI.java:617) ~[MineTweakerImplementationAPI$20.class:?]
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71519_b(MCServer.java:132) ~[MCServer$MCCommand.class:?]
	at net.minecraft.command.CommandHandler.func_71557_a(CommandHandler.java:219) ~[z.class:?]
	at com.matthewprenger.helpfixer.HelpFixer$1.func_71534_d(HelpFixer.java:33) ~[HelpFixer$1.class:1.0.7]
	at net.minecraft.command.CommandHelp.func_71515_b(SourceFile:38) ~[au.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
	at net.minecraft.server.MinecraftServer.func_71252_i(MinecraftServer.java:1410) [MinecraftServer.class:?]
	at net.minecraft.network.rcon.RConThreadClient.run(SourceFile:84) [oz.class:?]
	at java.lang.Thread.run(Thread.java:722) [?:1.7.0_21]
```

I'm running a 1.7.10 server with Forge 10.13.2.1342, and MineTweaker 3.0.9C

EDIT : there is no more exception if I add a slash before the command... But why does MT throw an exception with some commands ? I also have ForgeEssentials, maybe that's why some commands are blocked because of a lack of permissions

**Comment by jaredlll08** [comment]
It is most probably linked to ForgeEssentials, can you try without it?

**Comment by jaredlll08** [comment]
ok so, the problem with this is that there needs to be a player on the server for most of the Minetweaker commands to work, there is no way to fix this currently without causing other issues
