### ISSUE TITLE
Minetweaker crashing with Lord of the RIngs mod

### ISSUE THREAD

**Issue by keenerb** [stanhebben/MineTweaker3#173]
```
[B#299] [14:26:44] [Server thread/ERROR] [FML]: The following problems were captured during this phase
[B#299] [14:26:44] [Server thread/ERROR] [FML]: Caught exception from lotr
[B#299] java.lang.RuntimeException: java.lang.ClassCastException: minetweaker.mc1710.server.MCServer$MCCommand cannot be cast to net.minecraft.command.CommandBase
[B#299] at lotr.common.LOTRReflection.logFailure(LOTRReflection.java:61) ~[LOTRReflection.class:?]
[B#299] at lotr.common.LOTRReflection.removeCommand(LOTRReflection.java:306) ~[LOTRReflection.class:?]
[B#299] at lotr.common.LOTRMod.onServerStarting(LOTRMod.java:2610) ~[LOTRMod.class:?]
[B#299] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
[B#299] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
[B#299] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
[B#299] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
[B#299] at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[modpack.jar:?]
[B#299] at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
[B#299] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
[B#299] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
[B#299] at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
[B#299] at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
[B#299] at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
[B#299] at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
[B#299] at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
[B#299] at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[modpack.jar:?]
[B#299] at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[modpack.jar:?]
[B#299] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
[B#299] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
[B#299] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
[B#299] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
[B#299] at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
[B#299] at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
[B#299] at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
[B#299] at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
[B#299] at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
[B#299] at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
[B#299] at cpw.mods.fml.common.Loader.serverStarting(Loader.java:739) [Loader.class:?]
[B#299] at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
[B#299] at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:94) [bsx.class:?]
[B#299] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
[B#299] at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[B#299] Caused by: java.lang.ClassCastException: minetweaker.mc1710.server.MCServer$MCCommand cannot be cast to net.minecraft.command.CommandBase
[B#299] at lotr.common.LOTRReflection.removeCommand(LOTRReflection.java:286) ~[LOTRReflection.class:?]
[B#299] ... 31 more
```

Forge 1307, 3.0.9C Minetweaker

**Comment by stanhebben** [comment]
That's the lotr mod casting something without checking. It's clearly their bug - you'll have to bug the mod author about it. Should be easy for him to fix it.

**Comment by jaredlll08** [comment]
Their issue.
