### ISSUE TITLE
IItemStackAny error whilst trying to remove a recipe

### ISSUE THREAD

**Issue by SanAndreasP** [stanhebben/MineTweaker3#184]
**Minecraft**: 1.7.10
**Forge**: 1.7.10-10.13.3.1401-1710ls
**MineTweaker**: MineTweaker3-1.7.10-3.0.9C

**Problem**:
I maintain a mod called *VarietyChests*. Recently I had a discussion about recipe incompatibilities between my mod and MineTweaker: SanAndreasP/VarietyChests#8
Looking at the MineTweaker code I made a fix, which involves returning a standard ItemStack in the getRecipeOutput() method in my custom IRecipe implementation.
Assuming this will give MT the chance to find the recipe and remove it (or alter it, I don't know if MT has the abillity to "override" my IRecipe implementation), I made a little script to test it out:
```
val item = <varietychests:customchest>;
val chest = item.withTag({"chestType": "original"});
recipe.remove(chest);
```
To my surprise, this does not work and gives me following error in the log:
```
INFO: Adding command minetweaker
INFO: Adding minetweaker command mfr
ERROR: tests.zs:3 > could not find recipe
ERROR: Error executing tests.zs: minetweaker/api/item/IItemStackAny
java.lang.NoClassDefFoundError: minetweaker/api/item/IItemStackAny
	at Tests.__script__(tests.zs:3)
	at __ZenMain__.run(tests.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.processCommand(MCServer.java:124)
	at net.minecraft.command.CommandHandler.executeCommand(CommandHandler.java:96)
	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:788)
	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:764)
	at net.minecraft.network.play.client.C01PacketChatMessage.processPacket(C01PacketChatMessage.java:47)
	at net.minecraft.network.play.client.C01PacketChatMessage.processPacket(C01PacketChatMessage.java:68)
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241)
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)
Caused by: java.lang.ClassNotFoundException: minetweaker.api.item.IItemStackAny
	at java.lang.ClassLoader.findClass(ClassLoader.java:531)
	at stanhebben.zenscript.ZenModule$MyClassLoader.findClass(ZenModule.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 19 more
```
So, since I do not know what is causing this, nor do I know of any mistake I made on my side, I have to report this.

**Additional Info**:
If you want to take a look at my custom IRecipe class:
https://github.com/SanAndreasP/VarietyChests/blob/master/java/de/sanandrew/mods/varietychests/crafting/RecipePlainChests.java
And here is how I register the recipes:
https://github.com/SanAndreasP/VarietyChests/blob/master/java/de/sanandrew/mods/varietychests/util/VarietyChests.java#L111

**Comment by stanhebben** [comment]
MineTweaker checks if there recipe is an instance of the standard ShapedRecipes or ShapelessRecipes, or any of the oredict-supporting equivalents, or its subclasses. When the custom recipes is not a subclass of any of these, only the recipes.remove function will work. RemoveShapeless and removeShaped won't; since the recipes cannot be recognized.

At least recipes.remove should have worked, but apparently something went wrong during compilation of the script. For this case, withTag should have been onlyWithTag, but that won't be the cause of the crash. I will have to look into it.

**Comment by SanAndreasP** [comment]
For the first part, I thought so.
For the second: I will try the onlyWithTag method and see if that works. But even w/o any tag, just the item itself, it doesn't work and crashes with the exact same error `java.lang.NoClassDefFoundError: minetweaker/api/item/IItemStackAny`

**Comment by SanAndreasP** [comment]
Tried out the `onlyWithTag()` method:
```
val item = <varietychests:customchest>;
val chest = item.onlyWithTag({"chestType": "original"});
recipe.remove(chest);
```
and now I get this error:
```
INFO: Adding command minetweaker
INFO: Adding minetweaker command mfr
ERROR: tests.zs:3 > could not find recipe
ERROR: Error executing tests.zs: Truncated class file
java.lang.ClassFormatError: Truncated class file
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at stanhebben.zenscript.ZenModule$MyClassLoader.findClass(ZenModule.java:346)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at Tests.__script__(tests.zs:3)
	at __ZenMain__.run(tests.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI.onServerStart(MineTweakerImplementationAPI.java:555)
	at minetweaker.mc1710.MineTweakerMod.onServerAboutToStart(MineTweakerMod.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:834)
	at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:273)
	at net.minecraft.server.integrated.IntegratedServer.startServer(IntegratedServer.java:95)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:445)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)
```

**Comment by stanhebben** [comment]
Only now I notice your error.

It's *recipes*, not recipe. And after that, other bugs (known) mess up things.

**Comment by ZeroLevels** [comment]
Playing with it further, it would seem things are working somewhat now.  However, you can't select which recipes to remove through either **.withTag** or **.onlyWithTag**.  The former removes all recipes attached to the base ID rather than the chestType.  The latter has no effect at all.

To remove the ghost recipes even after changing/removing VarietyChests recipes, you have to disable the **B:"NEI Crafting Recipes Fix"** in VarietyChests' configuration file.

Not sure if this is what you meant about your other known bugs comment above, but I figured I'd elaborate for anyone else finding their way here.
