### ISSUE TITLE
Unexpected error when dumping loot settings

### ISSUE THREAD

**Issue by reteo** [stanhebben/MineTweaker3#185]
I am attempting to configure the loot settings for a custom modpack I'm designing.  However, when I attempt to dump the MT3 loot settings with "/mt loot" or "/minetweaker loot", I get the error message: "**An unknown error occurred while attempting to perform this command**".

In MultiMC, the following error precedes the above statement:

```
[16:12:03] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.GuiChat
[16:12:06] [Server thread/ERROR]: Couldn't process command: 'minetweaker loot'
java.lang.NullPointerException
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217) ~[add.class:?]
	at minetweaker.mc1710.item.MCItemStack.toString(MCItemStack.java:348) ~[MCItemStack.class:?]
	at java.lang.String.valueOf(String.java:2982) ~[?:1.8.0_45]
	at java.lang.StringBuilder.append(StringBuilder.java:131) ~[?:1.8.0_45]
	at minetweaker.api.vanilla.LootEntry.toString(LootEntry.java:47) ~[LootEntry.class:?]
	at minetweaker.MineTweakerImplementationAPI$13.execute(MineTweakerImplementationAPI.java:395) ~[MineTweakerImplementationAPI$13.class:?]
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610) ~[MineTweakerImplementationAPI$19.class:?]
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124) ~[MCServer$MCCommand.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[16:12:06] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command
```

In addition, the loot log does start, but doesn't seem to cover everything (I'm looking for the blacksmith's chest loot), so something stopped it dead in its tracks.

```
INFO: Adding command minetweaker
INFO: Adding minetweaker command mfr
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Restoring 1 recipes
INFO: Restoring 1 recipes
INFO: Restoring 1 recipes
INFO: Restoring 1 recipes
INFO: Restoring 1 recipes
INFO: Restoring 1 recipes
INFO: Removing minetweaker command mfr
INFO: Removing command minetweaker
INFO: Adding command minetweaker
INFO: Adding minetweaker command mfr
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
INFO: Removing 1 recipes
Loot chest contents:
Loot type: bonusChest
    <minecraft:stick> * 1 (weight 10, 1-3)
    <minecraft:planks> * 1 (weight 10, 1-3)
    <minecraft:log> * 1 (weight 10, 1-3)
    <minecraft:apple> * 1 (weight 5, 2-3)
    <minecraft:bread> * 1 (weight 3, 2-3)
    <minecraft:log2> * 1 (weight 10, 1-3)
    <ChromatiCraft:chromaticraft_item_shard> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:1> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:2> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:3> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:4> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:5> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:6> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:7> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:8> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:9> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:10> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:11> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:12> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:13> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:14> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:15> * 1 (weight 1, 1-5)
    <RotaryCraft:rotarycraft_item_shaftcraft:1> * 1 (weight 6, 1-5)
    <TConstruct:broadsword> * 1 (weight 10)
    <TConstruct:pickaxe>.withTag({InfiTool: {BaseDurability: 40, Head: 0, BaseAttack: 2, ToolEXP: 0 as long, HarvestLevel: 0, Attack: 2, RenderHead: 0, ModDurability: 0.0 as float, Handle: 0, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 0, Accessory: 0, MiningSpeed: 150, RenderAccessory: 0, ToolLevel: 1, Unbreaking: 0, Damage: 0, BonusDurability: 0, TotalDurability: 40, Modifiers: 0}, display: {Name: "§fStarter Pickaxe"}}) * 1 (weight 5, 1-1)
    <TConstruct:hatchet>.withTag({InfiTool: {BaseDurability: 40, Head: 0, BaseAttack: 4, ToolEXP: 0 as long, HarvestLevel: 0, Attack: 4, RenderHead: 0, ModDurability: 0.0 as float, Handle: 0, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 0, MiningSpeed: 150, ToolLevel: 1, Unbreaking: 0, Damage: 0, BonusDurability: 0, TotalDurability: 40, Modifiers: 0}, display: {Name: "§fStarter Hatchet"}}) * 1 (weight 5, 1-1)
Loot type: dungeonChest
    <minecraft:saddle> * 1 (weight 10, 1-1)
    <minecraft:iron_ingot> * 1 (weight 10, 1-4)
    <minecraft:bread> * 1 (weight 10, 1-1)
    <minecraft:wheat> * 1 (weight 10, 1-4)
    <minecraft:gunpowder> * 1 (weight 10, 1-4)
    <minecraft:string> * 1 (weight 10, 1-4)
    <minecraft:bucket> * 1 (weight 10, 1-1)
    <minecraft:golden_apple> * 1 (weight 1, 1-1)
    <minecraft:redstone> * 1 (weight 10, 1-4)
    <minecraft:record_13> * 1 (weight 10, 1-1)
    <minecraft:record_cat> * 1 (weight 10, 1-1)
    <minecraft:name_tag> * 1 (weight 10, 1-1)
    <minecraft:golden_horse_armor> * 1 (weight 2, 1-1)
    <minecraft:iron_horse_armor> * 1 (weight 5, 1-1)
    <minecraft:diamond_horse_armor> * 1 (weight 1, 1-1)
    <minecraft:enchanted_book> * 1 (weight 1, 1-1)
    <betterstorage:drinkingHelmet> * 1 (weight 1, 1-1)
    <Railcraft:tool.steel.sword> * 1 (weight 5, 1-1)
    <Railcraft:armor.steel.helmet> * 1 (weight 5, 1-1)
    <Railcraft:armor.steel.plate> * 1 (weight 5, 1-1)
    <Railcraft:armor.steel.legs> * 1 (weight 5, 1-1)
    <Railcraft:armor.steel.boots> * 1 (weight 5, 1-1)
    <OpenBlocks:technicolorGlasses> * 1 (weight 2, 1-1)
    <RandomThings:whitestone> * 1 (weight 3, 1-1)
    <TConstruct:heartCanister:1> * 1 (weight 5, 1-1)
    <ChromatiCraft:chromaticraft_item_shard> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:1> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:2> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:3> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:4> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:5> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:6> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:7> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:8> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:9> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:10> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:11> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:12> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:13> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:14> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:15> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_fragment> * 1 (weight 10, 1-1)
    <RotaryCraft:rotarycraft_item_shaftcraft:9> * 1 (weight 20, 6-18)
    <RotaryCraft:rotarycraft_item_shaftcraft:10> * 1 (weight 40, 1-12)
    <RotaryCraft:rotarycraft_item_canola> * 1 (weight 40, 1-12)
    <EnderIO:itemAlloy:6> * 1 (weight 15, 1-3)
    <EnderIO:itemConduitProbe> * 1 (weight 10, 1-1)
    <minecraft:quartz> * 1 (weight 20, 3-16)
    <minecraft:nether_wart> * 1 (weight 10, 1-4)
    <minecraft:ender_pearl> * 1 (weight 30, 1-2)
    <EnderIO:item.darkSteel_sword> * 1 (weight 5, 1-1)
    <EnderIO:item.darkSteel_boots> * 1 (weight 5, 1-1)
    <enhancedportals:portal_module:4> * 1 (weight 2, 1-1)
    <GardenContainers:pottery_pattern_dirty> * 1 (weight 1, 1-1)
    <HardcoreEnderExpansion:temple_caller> * 1 (weight 1)
    <HardcoreEnderExpansion:knowledge_note> * 1 (weight 6, 1-1)
Loot chest contents:
Loot type: bonusChest
    <minecraft:stick> * 1 (weight 10, 1-3)
    <minecraft:planks> * 1 (weight 10, 1-3)
    <minecraft:log> * 1 (weight 10, 1-3)
    <minecraft:apple> * 1 (weight 5, 2-3)
    <minecraft:bread> * 1 (weight 3, 2-3)
    <minecraft:log2> * 1 (weight 10, 1-3)
    <ChromatiCraft:chromaticraft_item_shard> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:1> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:2> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:3> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:4> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:5> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:6> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:7> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:8> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:9> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:10> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:11> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:12> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:13> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:14> * 1 (weight 1, 1-5)
    <ChromatiCraft:chromaticraft_item_shard:15> * 1 (weight 1, 1-5)
    <RotaryCraft:rotarycraft_item_shaftcraft:1> * 1 (weight 6, 1-5)
    <TConstruct:broadsword> * 1 (weight 10)
    <TConstruct:pickaxe>.withTag({InfiTool: {BaseDurability: 40, Head: 0, BaseAttack: 2, ToolEXP: 0 as long, HarvestLevel: 0, Attack: 2, RenderHead: 0, ModDurability: 0.0 as float, Handle: 0, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 0, Accessory: 0, MiningSpeed: 150, RenderAccessory: 0, ToolLevel: 1, Unbreaking: 0, Damage: 0, BonusDurability: 0, TotalDurability: 40, Modifiers: 0}, display: {Name: "§fStarter Pickaxe"}}) * 1 (weight 5, 1-1)
    <TConstruct:hatchet>.withTag({InfiTool: {BaseDurability: 40, Head: 0, BaseAttack: 4, ToolEXP: 0 as long, HarvestLevel: 0, Attack: 4, RenderHead: 0, ModDurability: 0.0 as float, Handle: 0, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 0, MiningSpeed: 150, ToolLevel: 1, Unbreaking: 0, Damage: 0, BonusDurability: 0, TotalDurability: 40, Modifiers: 0}, display: {Name: "§fStarter Hatchet"}}) * 1 (weight 5, 1-1)
Loot type: dungeonChest
    <minecraft:saddle> * 1 (weight 10, 1-1)
    <minecraft:iron_ingot> * 1 (weight 10, 1-4)
    <minecraft:bread> * 1 (weight 10, 1-1)
    <minecraft:wheat> * 1 (weight 10, 1-4)
    <minecraft:gunpowder> * 1 (weight 10, 1-4)
    <minecraft:string> * 1 (weight 10, 1-4)
    <minecraft:bucket> * 1 (weight 10, 1-1)
    <minecraft:golden_apple> * 1 (weight 1, 1-1)
    <minecraft:redstone> * 1 (weight 10, 1-4)
    <minecraft:record_13> * 1 (weight 10, 1-1)
    <minecraft:record_cat> * 1 (weight 10, 1-1)
    <minecraft:name_tag> * 1 (weight 10, 1-1)
    <minecraft:golden_horse_armor> * 1 (weight 2, 1-1)
    <minecraft:iron_horse_armor> * 1 (weight 5, 1-1)
    <minecraft:diamond_horse_armor> * 1 (weight 1, 1-1)
    <minecraft:enchanted_book> * 1 (weight 1, 1-1)
    <betterstorage:drinkingHelmet> * 1 (weight 1, 1-1)
    <Railcraft:tool.steel.sword> * 1 (weight 5, 1-1)
    <Railcraft:armor.steel.helmet> * 1 (weight 5, 1-1)
    <Railcraft:armor.steel.plate> * 1 (weight 5, 1-1)
    <Railcraft:armor.steel.legs> * 1 (weight 5, 1-1)
    <Railcraft:armor.steel.boots> * 1 (weight 5, 1-1)
    <OpenBlocks:technicolorGlasses> * 1 (weight 2, 1-1)
    <RandomThings:whitestone> * 1 (weight 3, 1-1)
    <TConstruct:heartCanister:1> * 1 (weight 5, 1-1)
    <ChromatiCraft:chromaticraft_item_shard> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:1> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:2> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:3> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:4> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:5> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:6> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:7> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:8> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:9> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:10> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:11> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:12> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:13> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:14> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_shard:15> * 1 (weight 2, 2-8)
    <ChromatiCraft:chromaticraft_item_fragment> * 1 (weight 10, 1-1)
    <RotaryCraft:rotarycraft_item_shaftcraft:9> * 1 (weight 20, 6-18)
    <RotaryCraft:rotarycraft_item_shaftcraft:10> * 1 (weight 40, 1-12)
    <RotaryCraft:rotarycraft_item_canola> * 1 (weight 40, 1-12)
    <EnderIO:itemAlloy:6> * 1 (weight 15, 1-3)
    <EnderIO:itemConduitProbe> * 1 (weight 10, 1-1)
    <minecraft:quartz> * 1 (weight 20, 3-16)
    <minecraft:nether_wart> * 1 (weight 10, 1-4)
    <minecraft:ender_pearl> * 1 (weight 30, 1-2)
    <EnderIO:item.darkSteel_sword> * 1 (weight 5, 1-1)
    <EnderIO:item.darkSteel_boots> * 1 (weight 5, 1-1)
    <enhancedportals:portal_module:4> * 1 (weight 2, 1-1)
    <GardenContainers:pottery_pattern_dirty> * 1 (weight 1, 1-1)
    <HardcoreEnderExpansion:temple_caller> * 1 (weight 1)
    <HardcoreEnderExpansion:knowledge_note> * 1 (weight 6, 1-1)
Seeds:
Seed: null - 10
```
Here is the full log of the session.

http://paste.ee/p/z8AOa

Please let me know if any other information would be required.

**Comment by Techokami** [comment]
I am having the same issue, in an instance with only MineTweaker and OpenComputers present. It may be due to how OpenComputers registers its loot...

**Comment by reteo** [comment]
After removing OpenComputers, the loot list was written without complaint.  I would say that a mod interaction issue is most likely.

**Comment by Techokami** [comment]
Yeah, OpenComputers uses special tricks for registering loot. This way, OC only has to register one loot item, which becomes a randomized loot disk upon generation. This allows for multiple loot disks without polluting the loot table (a thing that was discovered the hard way with Garden Collection and its pottery stamp loot items)

All we can do now is call in the OpenComputers dev and get a dialogue going between him and the dev(s) of MineTweaker.

Paging @fnuecke for support!

**Comment by fnuecke** [comment]
That's probably because I'm using an invalid `ItemStack` as the default item -- i.e. one with `getItem() == null`. Now before you sue me, I'm aware that that's ugly, but given that `ChestGetHooks.generateStacks` explicitly checks for that (and would NPE if the whole stack were `null`) I always assumed that's how it's meant to be used when wanting to enforce the use of `WeightedRandomChestContent.generateChestContents`; and I'd actually recommend adding a check for that (since others may well have come to the same conclusion). But I suppose I can just make it spit out empty floppies as default item as a safeguard...

**Comment by fnuecke** [comment]
All right, made that change because why not. Please give the [latest a dev build](http://ci.cil.li/job/OpenComputers-dev-MC1.7.10/) a try and see if that fixes it for you.

**Comment by reteo** [comment]
Yup, looks like the latest OC fixed the problem.  Loot tables were generated without a hiccup.  Thanks!
