### ISSUE TITLE
Method code too large!

### ISSUE THREAD

**Issue by Dream-Master** [stanhebben/MineTweaker3#212]
Get the following error.

````````````````````````````````````````````````````````````````````````````````
ERROR: Error executing Thaumcraft.zs: Method code too large!
java.lang.RuntimeException: Method code too large!
	at org.objectweb.asm.MethodWriter.a(Unknown Source)
	at org.objectweb.asm.ClassWriter.toByteArray(Unknown Source)
	at stanhebben.zenscript.ZenModule.compileScripts(ZenModule.java:133)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:153)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI.onServerStart(MineTweakerImplementationAPI.java:555)
	at minetweaker.mc1710.MineTweakerMod.onServerAboutToStart(MineTweakerMod.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:838)
	at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:273)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callBoolean(Reflector.java:363)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:150)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)`

````````````````````````````````````````````````````````````````````````````````

**Comment by Dream-Master** [comment]
I think i coding to much my file is to loooooooooooong ;-)

**Comment by stanhebben** [comment]
Erm.. ok. I'll think about how to fix this in the next version. Mind to post a link to the offending script?

Since this is not a common issue, I'll leave it as is. The workaround for now would be to either split the script into multiple smaller scripts, or to split the functionality into multiple functions, with the main code calling the other functions, like so:

```
function doA() {
    ...
}

function doB() {
    ...
}

doA();
doB();
```

do

**Comment by Dream-Master** [comment]
Yes split the files but thaumcraft have so many variations of Wands that it need a lot of code.
1,2 MB of Code already.
i think i been the first person hit the limit ;-)
proud a bit of my self ;-)

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/commit/c6abda91ca6a40fb49948b7bd046beeb8b85c139

**Comment by jaredlll08** [comment]
No real fix for this, even java has this problem

**Comment by Blue64** [comment]
@Dream-Master not sure if you ever fixed this, but perhaps splitting the file up would help (probably would), so you could do
```
Thaumcraft_A1.zs for Recipe Removals
Thaumcraft_A2.zs for OreDict Corrections
Thaumcraft_A3.zs for Recipes
```
and if you needed more you could just expand the number of `.zs` files, perhaps something like 
```
Thaumcraft_A1_A.zs
Thaumcraft_A1_B.zs
Thaumcraft_A1_C.zs
Thaumcraft_A1_D.zs
Thaumcraft_A1_E.zs
Thaumcraft_A1_F.zs
Thaumcraft_A1_G.zs
Thaumcraft_A1_H.zs
Thaumcraft_A1_I.zs
Thaumcraft_A1_J.zs
Thaumcraft_A1_K.zs
Thaumcraft_A1_L.zs
Thaumcraft_A1_M.zs
Thaumcraft_A1_N.zs
Thaumcraft_A1_O.zs
Thaumcraft_A1_P.zs
Thaumcraft_A1_Q.zs
Thaumcraft_A1_R.zs
Thaumcraft_A1_S.zs
Thaumcraft_A1_T.zs
Thaumcraft_A1_U.zs
Thaumcraft_A1_V.zs
Thaumcraft_A1_W.zs
Thaumcraft_A1_X.zs
Thaumcraft_A1_Y.zs
Thaumcraft_A1_Z.zs
Thaumcraft_A2_A.zs
Thaumcraft_A2_B.zs
Thaumcraft_A2_C.zs
Thaumcraft_A2_D.zs
Thaumcraft_A2_E.zs
Thaumcraft_A2_F.zs
Thaumcraft_A2_G.zs
Thaumcraft_A2_H.zs
Thaumcraft_A2_I.zs
Thaumcraft_A2_J.zs
Thaumcraft_A2_K.zs
Thaumcraft_A2_L.zs
Thaumcraft_A2_M.zs
Thaumcraft_A2_N.zs
Thaumcraft_A2_O.zs
Thaumcraft_A2_P.zs
Thaumcraft_A2_Q.zs
Thaumcraft_A2_R.zs
Thaumcraft_A2_S.zs
Thaumcraft_A2_T.zs
Thaumcraft_A2_U.zs
Thaumcraft_A2_V.zs
Thaumcraft_A2_W.zs
Thaumcraft_A2_X.zs
Thaumcraft_A2_Y.zs
Thaumcraft_A2_Z.zs
Thaumcraft_A3_A.zs
Thaumcraft_A3_B.zs
Thaumcraft_A3_C.zs
Thaumcraft_A3_D.zs
Thaumcraft_A3_E.zs
Thaumcraft_A3_F.zs
Thaumcraft_A3_G.zs
Thaumcraft_A3_H.zs
Thaumcraft_A3_I.zs
Thaumcraft_A3_J.zs
Thaumcraft_A3_K.zs
Thaumcraft_A3_L.zs
Thaumcraft_A3_M.zs
Thaumcraft_A3_N.zs
Thaumcraft_A3_O.zs
Thaumcraft_A3_P.zs
Thaumcraft_A3_Q.zs
Thaumcraft_A3_R.zs
Thaumcraft_A3_S.zs
Thaumcraft_A3_T.zs
Thaumcraft_A3_U.zs
Thaumcraft_A3_V.zs
Thaumcraft_A3_W.zs
Thaumcraft_A3_X.zs
Thaumcraft_A3_Y.zs
Thaumcraft_A3_Z.zs
```
you can see how exponential that gets. if _THAT_ isn't big enough, you can **_STILL_** use Numbers after the Alphabetized Letters.
