### ISSUE TITLE
Any idea why Ex Astris Rebirth ore blocks don't respond to their names?

### ISSUE THREAD

**Issue by dualinfinities** [stanhebben/MineTweaker3#213]
Chat says MT cannot resolve the name of the item
The name according to MT: <exastrisrebirth:zinc_dust> 
Name in my script: <exastrisrebirth:zinc_dust>
This is the MT log regarding the error:
ERROR: Error executing OreUnity.zs: null
java.lang.NullPointerException
	at minetweaker.mc1710.furnace.MCFurnaceManager.addRecipe(MCFurnaceManager.java:58)
	at OreUnity.__script__(OreUnity.zs:235)
	at __ZenMain__.run(OreUnity.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by jaredlll08** [comment]
Can I please have the script that was used

**Comment by dualinfinities** [comment]
fixed in latest version of minetweaker.
