### ISSUE TITLE
help command broken after adding minetweaker 

### ISSUE THREAD

**Issue by mindforger** [stanhebben/MineTweaker3#218]
i just added MineTweaker to my Modlist and then wanted to check what commands are available ...

http://pastebin.com/VvW8iXwx

it worked right before i added MT to the list!

3.0.9C Forge 1490

**Comment by jaredlll08** [comment]
Please update and try with 3.0.10

**Comment by mindforger** [comment]
will do this evening

**Comment by mindforger** [comment]
seems to be fixed, but specific help  with /help <cmd> seems still to be broken, i have to update my other mods before i can test again

**Comment by ilya-pirogov** [comment]
still doesn't work with rcon

```
[23:44:21] [RCON Client #7/INFO] [STDOUT]: [minetweaker.mc1710.server.MCServer:getPlayer:73]: Unsupported command sender: net.minecraft.network.rcon.RConConsoleSource@8f51617
[23:44:21] [RCON Client #7/INFO] [STDOUT]: [minetweaker.mc1710.server.MCServer:getPlayer:74]: player name: Rcon
[23:44:21] [RCON Client #7/ERROR]: Couldn't process command: 'help'
java.lang.NullPointerException
        at minetweaker.mc1710.server.MCServer.isOp(MCServer.java:61) ~[MCServer.class:?]
        at minetweaker.MineTweakerImplementationAPI$20.canExecute(MineTweakerImplementationAPI.java:649) ~[MineTweakerImplementationAPI$20.class:?]
        at minetweaker.mc1710.server.MCServer$MCCommand.func_71519_b(MCServer.java:132) ~[MCServer$MCCommand.class:?]
        at net.minecraft.command.CommandHandler.func_71557_a(CommandHandler.java:219) ~[z.class:?]
        at net.minecraft.command.CommandHelp.func_71534_d(SourceFile:83) ~[au.class:?]
        at net.minecraft.command.CommandHelp.func_71515_b(SourceFile:38) ~[au.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
        at net.minecraft.server.MinecraftServer.func_71252_i(MinecraftServer.java:1410) [MinecraftServer.class:?]
        at net.minecraft.network.rcon.RConThreadClient.run(SourceFile:84) [oz.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
```

**Comment by jaredlll08** [comment]
Hey @ilya-pirogov if I gave you a version that *should* add Rcon, could you test it for me?

**Comment by Blue64** [comment]
I've not heard of Rcon, which mod is that?

**Comment by jaredlll08** [comment]
It is a method to access a server command line. 
Stands for Remote Connection iirc

**Comment by Blue64** [comment]
I didn't know that until you taught it to me ```:)``` thank you ```:)``` I will most likely use this information eventually ```:)``` it's always nice to learn new things.

**Comment by jaredlll08** [comment]
Well I have no idea how to actually use it, I just know of it.

**Comment by Blue64** [comment]
That in it's self is the first step to using it! ```:D``` See? You're better at using it than you thought already! ```:P```

**Comment by Blue64** [comment]
Upon actually reading the log, I recognize this error!  Try re-logging, or perhaps even re-launching, that's what I do to fix it. It's a random error, and I've no idea what is actually causing it lol

**Comment by jaredlll08** [comment]
Nope, the error is that minetweaker doesn't support Rcon, or well it didn't, until I added it 5 minutes ago.

**Comment by Blue64** [comment]
I play offline single player By The Way, so totally not related to any server issues lol my ```/help 1``` ~ ```/help 14``` work just fine, I never actually tried to use the help command for information about a command, I normally just type the first word and read the error, using Tab Key to fill in the gaps.

That's another thing, I'm pretty sure that the entire command option gets corrupted. Potentially a Forge/MineCraft issue? Idk how ```/help``` violates the Terms of Use half the time, yet is perfectly fine the other half lol

**Comment by Blue64** [comment]
If that were the case, would re-logging fix it?

**Comment by jaredlll08** [comment]
Well not exactly, Rcon isn't a mod, it is a vanilla minecraft mechanic, it would be like sshing into the minecraft server, so now, Minetweaker doesn't know how to handle it, which is evident in his crash log:
```
[23:44:21] [RCON Client #7/INFO] [STDOUT]: [minetweaker.mc1710.server.MCServer:getPlayer:73]: Unsupported command sender: net.minecraft.network.rcon.RConConsoleSource@8f51617
[23:44:21] [RCON Client #7/INFO] [STDOUT]: [minetweaker.mc1710.server.MCServer:getPlayer:74]: player name: Rcon ```

**Comment by Blue64** [comment]
That may potentially be unrelated as well lol because I'm fairly sure I have never had an RCon Error, but I'd need to verify that the next time it happens.

The hardest part of the error is it doesn't crash, it just reads similar to the error within PasteBin (I actually had that happen just this morning, tried ```/mt hand``` and it failed, I was like "Wha-?" Tried ```/help```, errored, I logged out, logged in, everything works, Idk how, Idk why), but it only reads it in the console log (Forge latest log)

**Comment by ilya-pirogov** [comment]
@jaredlll08 Sure, I will

Thanks.

**Comment by jaredlll08** [comment]
@ilya-pirogov try this version:
http://www.blamejared.com/content/CraftTweaker-Customized-1.7.10-3.0.2.jar

**Comment by ilya-pirogov** [comment]
@jaredlll08 This version works great. Thank you.

**Comment by jaredlll08** [comment]
OK cool! That is perfect! I'll make a release soon (just note,  that is my
unofficial continuation of minetweaker,  CraftTweaker)
