### ISSUE TITLE
[3.0.10] Setting Block Hardness doesnt work

### ISSUE THREAD

**Issue by itanshi** [stanhebben/MineTweaker3#239]
Examples I've used, first is from wiki entry
```zenscript
<minecraft:gold_ore>.hardness = 3;
```
ERROR: Error executing ores.zs:
cpw.mods.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.langNoSuchFieldException: blockHardness
```zenscript
<minecraft:gold_ore.hardness = 3>;
```
ERROR: ?:1: Could not resolve < minecraft:gold_ore . hardness = 3 >
```zenscript
<minecraft:gold_ore>.hardness(3);
```
ERROR: ?:1 > no method with that name available
```zenscript
(<minecraft:gold_ore>.hardness = 3);
```
ERROR: Error executing ores.zs:
cpw.mods.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.langNoSuchFieldException: blockHardness
```zenscript
(<minecraft:gold_ore>.hardness = 3;)
```
ERROR Parsing ores.zs:1 -- ) expected
```zenscript
<minecraft:gold_ore>.hardness=3;
```
ERROR: Error executing ores.zs:
cpw.mods.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.langNoSuchFieldException: blockHardness
```zenscript
(<minecraft:gold_ore>).hardness=3; 
```
ERROR: Error executing ores.zs:
cpw.mods.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.langNoSuchFieldException: blockHardness

**Comment by jaredlll08** [comment]
What minecraft version?

**Comment by itanshi** [comment]
1.7.10

**Comment by jaredlll08** [comment]
And forge version?

**Comment by itanshi** [comment]
10.13.4.1492

**Comment by jaredlll08** [comment]
using the script
<minecraft:gold_ore>.hardness = 3;
using 1.7.10 and the same forge, I cannot reproduce this.
Can you try with just minetweaker?

**Comment by itanshi** [comment]
The code you show was unformatted by github,
```zenscript
<minecraft:gold_ore>.hardness = 3;
```
right?

Same error as before, only mods loaded are minetweaker3, waila and waila harvestability

**Comment by jaredlll08** [comment]
Yea, I forgot formatting, exactly as you have it there, can I get the
minetweaker.log please

**Comment by itanshi** [comment]
http://pastebin.com/uc4gBmTe

**Comment by jaredlll08** [comment]
What is on line 1? It is showing an error there

**Comment by itanshi** [comment]
I redid the test

Line 1/1
```zenscript
<minecraft:gold_ore>.hardness=10;
```

http://pastebin.com/WRXDiFUr

**Comment by jaredlll08** [comment]
I really can't reproduce this.

**Comment by itanshi** [comment]
Well, I'm using the latest java 8. Should I try different java versions?

**Comment by jaredlll08** [comment]
In using the same, what mod list?

**Comment by itanshi** [comment]
Waila, waila harvestability and minetweaker 3

**Comment by jaredlll08** [comment]
Try without waila please

**Comment by itanshi** [comment]
Same error

**Comment by jaredlll08** [comment]
Ok then this is weird, but I really can't reproduce this at all :/

**Comment by jaredlll08** [comment]
apparently this was fixed

**Comment by boop5** [comment]
I have the same error with `MineTweaker3-1.7.10-3.0.10B` on 1.7.10 (forge10.13.4.1614)

I tried this

```
<ExtraUtilities:endConstructor>.hardness = 3;
```

and 

```
<minecraft:gold_ore>.hardness=10;
```

gamelog

```
[14:55:25] [Client thread/INFO]: [CHAT] ERROR: Error executing ExpensiveIronChest.zs: cpw.mods.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: blockHardness
[14:55:25] [Client thread/INFO]: [CHAT] Scripts reloaded
[14:57:30] [Client thread/INFO]: [CHAT] ERROR: Error executing ExpensiveIronChest.zs: cpw.mods.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: blockHardness
[14:57:30] [Client thread/INFO]: [CHAT] Scripts reloaded
[14:58:03] [Client thread/INFO]: [CHAT] ERROR: Error parsing ExpensiveIronChest.zs:17 -- ; expected
[14:58:03] [Client thread/INFO]: [CHAT] Scripts reloaded
[14:58:20] [Client thread/INFO]: [CHAT] ERROR: Error executing ExpensiveIronChest.zs: cpw.mods.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: blockHardness
[14:58:20] [Client thread/INFO]: [CHAT] Scripts reloaded
[14:58:51] [Client thread/INFO]: [CHAT] ERROR: Error executing ExpensiveIronChest.zs: cpw.mods.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: blockHardness
[14:58:51] [Client thread/INFO]: [CHAT] Scripts reloaded
```

minetweaker.log

```
INFO: Adding recipe for Torch
ERROR: Error executing ExpensiveIronChest.zs: cpw.mods.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: blockHardness
cpw.mods.fml.relauncher.ReflectionHelper$UnableToAccessFieldException: cpw.mods.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: blockHardness
    at cpw.mods.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:121)
    at minetweaker.mc1710.actions.SetBlockHardnessAction.<init>(SetBlockHardnessAction.java:28)
    at minetweaker.mc1710.item.MCItemStack.setBlockHardness(MCItemStack.java:130)
    at ExpensiveIronChest.__script__(ExpensiveIronChest.zs:17)
    at __ZenMain__.run(ExpensiveIronChest.zs)
    at minetweaker.runtime.MTTweaker.load(MTTweaker.java:163)
    at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:656)
    at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:83)
    at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:642)
    at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
    at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
    at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at fastcraft.at.a(F:978)
    at fastcraft.H.aq(F:36)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: cpw.mods.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: blockHardness
    at cpw.mods.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:94)
    at cpw.mods.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:117)
    ... 23 more
Caused by: java.lang.NoSuchFieldException: blockHardness
    at java.lang.Class.getDeclaredField(Class.java:2062)
    at cpw.mods.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:85)
    ... 24 more
INFO: Removing 2 recipes
INFO: Adding recipe for Platinum Seeds
```
