### ISSUE TITLE
Problem with removing items from NEI

### ISSUE THREAD

**Issue by EfficiencyVI** [stanhebben/MineTweaker3#260]
Hi, I don't want to have 200 pages of items in my modpack so I removed e. g. all the Forge microblocks like this:

```
mods.nei.NEI.hide(<ForgeMicroblock:microblock:*>);
```

That worked fine. However I also don't want 5 pages of bee stuff when I can just look up the queens for every species, so I tried this:

```
mods.nei.NEI.hide(<Forestry:beePrincessGE:*>);
mods.nei.NEI.hide(<Forestry:beeDroneGE:*>);
mods.nei.NEI.hide(<gendustry:GeneSample:*>);
```

And unfortunately none of these entries work.

**Comment by Yulife** [comment]
I think bees use NBT-Data to distuingish themselves. Just a vague guess, remove the :* after the bee entry.

**Comment by EfficiencyVI** [comment]
Yes, they use all metaid 0. How ever removing the :* does not change anything.

**Comment by EfficiencyVI** [comment]
Another bug, when I restart the game all Microblocks are back even though the log says:

```
INFO: Hiding item.microblock in NEI
INFO: Hiding item.extrautils:microblocks.32767 in NEI
```

In my file I have:

```
mods.nei.NEI.hide(<ForgeMicroblock:microblock:*>);
mods.nei.NEI.hide(<ExtraUtilities:microblocks:*>);
```

So most of the Forge Microblocks and the Extra Utilities Microblocks are visible until I run /mt reload. Then they disappear.

**Comment by Yulife** [comment]
Well, NEI support is **really** wonky. There are dozens of issues on this repo for it already :)

**Comment by EfficiencyVI** [comment]
Another thing:

```
ERROR: Error executing NEI.zs: 5
java.lang.ArrayIndexOutOfBoundsException: 5
	at mantle.items.abstracts.CraftingItem.func_77667_c(CraftingItem.java:70)
	at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:361)
	at minetweaker.mods.nei.NEI$NEIHideItemAction.describe(NEI.java:127)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:55)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:169)
	at minetweaker.mods.nei.NEI.hide(NEI.java:36)
	at NEI.__script__(NEI.zs:162)
	at __ZenMain__.run(NEI.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:163)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:651)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:637)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

The line is

```
mods.nei.NEI.hide(<TConstruct:fletching:*>);
```

When I remove the :* the error disappears but the items are still visible. For the most parts I moved everything to INpure core which is much more reliable. But I seem to be the first one who actually test things like that. :-)

**Comment by Voidi** [comment]
Really the first? https://github.com/stanhebben/MineTweaker3/issues?utf8=%E2%9C%93&q=NEI

**Comment by EfficiencyVI** [comment]
Really!

https://github.com/stanhebben/MineTweaker3/issues?utf8=%E2%9C%93&q=NEI+beedrone*
https://github.com/stanhebben/MineTweaker3/issues?utf8=%E2%9C%93&q=NEI+tconstruct*

**Comment by Voidi** [comment]
My point is: we really know that the NEI support in Minetweaker is nearly unusable.
This not restricted to specific mods, it's a genral general problem.

**Comment by jaredlll08** [comment]
1.7 is no longer supported. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately
