### ISSUE TITLE
Mod crafting tables lose recipes (ConcurrentModificationException)

### ISSUE THREAD

**Issue by codewarrior0** [stanhebben/MineTweaker3#297]
When loading an existing single-player game with FTB Infinity Evolved in expert mode, which has around a thousand lines of MineTweaker scripts, crafting tables from LogisticsPipes will lose their saved recipes. 

This traceback is found in the log file, curiously mixed in with MineTweaker's startup output:

```
[15:11:49] [Client thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:111]: Loading scripts
[15:11:49] [Client thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:158]: MineTweaker: Loading 1-InitialScripts.zs
[15:11:49] [Client thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:158]: MineTweaker: Loading AdvancedSolars.zs
[15:11:49] [Client thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:158]: MineTweaker: Loading AppliedEnergistics.zs
[15:11:49] [Server thread/ERROR] [FML]: A TileEntity logisticspipes.blocks.crafting.LogisticsCraftingTableTileEntity(logisticspipes.blocks.crafting.LogisticsCraftingTableTileEntity) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_65]
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_65]
	at logisticspipes.blocks.crafting.LogisticsCraftingTableTileEntity.cacheRecipe(LogisticsCraftingTableTileEntity.java:71) ~[LogisticsCraftingTableTileEntity.class:0.9.3.local]
	at logisticspipes.blocks.crafting.LogisticsCraftingTableTileEntity.func_145839_a(LogisticsCraftingTableTileEntity.java:307) ~[LogisticsCraftingTableTileEntity.class:0.9.3.local]
	at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:116) [aor.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:496) [aqk.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189) [AsynchronousExecutor$Task.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.get(AsynchronousExecutor.java:165) [AsynchronousExecutor$Task.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:341) [AsynchronousExecutor.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at logisticspipes.utils.TileBuffer.refresh(TileBuffer.java:44) [TileBuffer.class:0.9.3.local]
	at logisticspipes.utils.TileBuffer.<init>(TileBuffer.java:28) [TileBuffer.class:0.9.3.local]
	at logisticspipes.utils.TileBuffer.makeBuffer(TileBuffer.java:102) [TileBuffer.class:0.9.3.local]
	at logisticspipes.pipes.basic.LogisticsTileGenericPipe.getTileCache(LogisticsTileGenericPipe.java:796) [LogisticsTileGenericPipe.class:0.9.3.local]
	at logisticspipes.pipes.basic.LogisticsTileGenericPipe.refreshTileCacheOnSide(LogisticsTileGenericPipe.java:1115) [LogisticsTileGenericPipe.class:0.9.3.local]
	at logisticspipes.routing.pathfinder.changedetection.TEControl$1.call(TEControl.java:63) [TEControl$1.class:0.9.3.local]
	at logisticspipes.ticks.QueuedTasks.tickEnd(QueuedTasks.java:45) [QueuedTasks.class:0.9.3.local]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_999_QueuedTasks_tickEnd_ServerTickEvent.invoke(.dynamic) [?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[...dozens more errors...]

[15:11:50] [Client thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:158]: MineTweaker: Loading ComputerCraft.zs
[15:11:50] [Client thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:158]: MineTweaker: Loading DraconicEvolution.zs
[15:11:50] [Client thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:158]: MineTweaker: Loading DungeonLoot.zs
[15:11:50] [Client thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:158]: MineTweaker: Loading EnderIO.zs
[15:11:50] [Client thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:158]: MineTweaker: Loading EnderStorage.zs
[15:11:50] [Client thread/INFO] [STDOUT]: [minetweaker.runtime.MTTweaker:load:158]: MineTweaker: Loading ExtraUtilities.zs
[...dozens more scripts...]
```

Similar problems have been reported with BuildCraft auto-crafting tables and Forestry workbenches. [See this issue](https://github.com/RS485/LogisticsPipes/issues/868) for more reports.

**Comment by codewarrior0** [comment]
FYI, the comodified array is the one returned by `net.minecraft.item.crafting.CraftingManager.getInstance().getRecipeList()`

**Comment by codewarrior0** [comment]
Whoops, almost forgot. Minecraft 1.7.10, Java JRE 1.8.0_65, MineTweaker3-1.7.10-3.0.10B.

**Comment by Blue64** [comment]
perhaps splitting the ```FTB Infinity Evolved (Expert Mode)```'s MineTweaker ```.zs``` file into multiple ```.zs``` files would solve this until someone can review this issue?

**Comment by codewarrior0** [comment]
I doubt that would help at all. Expert mode has 46 `.zs` files already, segregated by mod.

It seems to me like MineTweaker doesn't need to run client-side on client login when in single-player mode.

**Comment by Blue64** [comment]
do the client-side scripts by chance have the failsafe of removing all the recipes that server-side added?

**Comment by codewarrior0** [comment]
They are the same scripts in each case. Some of them do remove recipes.

The point is, in single-player mode, the scripts seem to be running twice.

**Comment by codewarrior0** [comment]
The only workaround I can think of is to run my single-player game as a local server and connect to it with a separate client.

**Comment by Blue64** [comment]
well if the recipe gets removed before it gets added each time, there should be no problem even if it runs 20 times, other than the processing & RAM usage and the error log. Worth looking into, but if the reference I just linked pans out, there should be a workaround available where you can explicitly load certain ones, which would solve any repetitive issues as a patch until it can actually be fixed.

**Comment by codewarrior0** [comment]
It's not a problem that the scripts run twice.

It's a problem that the scripts run on the client thread while the server thread is loading chunks. The linked issue has no relevance.

**Comment by codewarrior0** [comment]
Again, they are the same scripts in each case. There is no "server scripts" and "client scripts" distinction. The problem only arises in single-player mode, where the server and client are running in the same process, thus they both access the same recipe list. The client modifies the recipe list while the server is accessing it.

**Comment by Blue64** [comment]
Ah, that would be a problem, yes. Quick question, is there any of [this issue](https://github.com/stanhebben/MineTweaker3/issues/298) happening? As I've never seen your script compilation, I wouldn't know, but the primary error (concurrent whatever) is identical, so I gotta ask (```ctrl```+```f``` is your friend lol)

**Comment by codewarrior0** [comment]
There is none of the error in that that issue happening. If it were the case, I would expect to see a lot of reports of FTB Infinity servers that are completely broken due to the MT misconfiguration mentioned in that issue.

That issue itself is a bit alarming because it indicates a concurrent modification error on an unmodifiable array!

**Comment by Blue64** [comment]
Lol yeah, mirror is like that. Some modification can be changed multiple times (recipes), some can't (mirrored OreDict). In that case it's because the OreDict was being modified with info it already had due to the mirror, compounded by the fact that it was mirrored, thus the double error. Took me a moment to spot the problem, but it turned out to be simple User Input Error.

Good point, I guess we'd have heard about it sooner if that was the case. Hrm… let me run a few tests to see how my scripts load and I'll get back to ya. I play offline single player with my firewall denying any connections, so it may behave differently. I'll let you know once I have my log, though I haven't fully fleshed out my scripts yet, so I won't be throwing the Unmodifiable errors, but the loading should still run.

**Comment by jaredlll08** [comment]
The problem with this is how logistics pipes are accessing the recipe list. I suggest that you make an issue on their side, saying that they should use a simple 'for loop' instead of how they currently do it

**Comment by codewarrior0** [comment]
The problem also happens with Forestry worktables and BuildCraft auto-workbenches. Shall I open issues with them, too?

**Comment by codewarrior0** [comment]
They do use a simple 'for loop' for this. The loop is at [LogisticsCraftingTableTileEntity.java:71](https://github.com/RS485/LogisticsPipes/blob/dev/common/logisticspipes/blocks/crafting/LogisticsCraftingTableTileEntity.java#L71), iterating over the array returned from `net.minecraft.item.crafting.CraftingManager.getInstance().getRecipeList()`

As I've pointed out, the problem exists because it is iterating over this array on the server thread, while at the same time MineTweaker is modifying recipes on the client thread. In a single-player game, both threads share the same recipe list.

**Comment by jaredlll08** [comment]
uh yea... that isn't a simple 'for loop' a simple one would be

```
for(int i = 0;i<CraftingUtil.getRecipeList().size();i++){
IRecipe r = CraftUtils.getRecipeList().get(i);
	if (r.matches(craftInv, getWorldObj())) {
	list.add(r);
	}
}
```

**Comment by codewarrior0** [comment]
I'm trying to explain to you that this is a concurrency issue. The for loop you gave also suffers concurrency issues - what if the size of the recipe list changes during iteration? You will get an OOB exception rather than a comodification exception.

Again, the problem is that in a single-player game, MineTweaker is executing all of its scripts twice on different threads.

First, it executes scripts on the server thread during server startup. Later, the game creates a client thread and connects to the server. MineTweaker executes scripts a second time on the client thread. This is pointless, as the recipe list already has all the changes made by those scripts. It also causes concurrency problems because the server thread will access the recipe list at the same time the client thread is modifying it.
