### ISSUE TITLE
AddAll.undo kicking players when they join

### ISSUE THREAD

**Issue by TerdyTheTerd** [stanhebben/MineTweaker3#298]
So the other night I was adding Uranium to the Yellorium oreDict with the following two lines 

"<ore:ingotYellorium>.mirror(<ore:ingotUranium>);
<ore:ingotUranium>.addAll(<ore:ingotYellorium>);"

At first it was all fine and dandy, however after leaving the server and trying to rejoin it always kicks me (and all other players who try to join after I made that edit) with following error in the log 

"[18:36:21] [Server thread/ERROR]: Couldn't process command: 'mt reload'
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_51]
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_51]
	at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList$2.next(OreDictionary.java:625) ~[OreDictionary$UnmodifiableArrayList$2.class:1.7.10-1492.152]
	at minetweaker.mc1710.oredict.MCOreDictEntry$ActionAddAll.undo(MCOreDictEntry.java:376) ~[MCOreDictEntry$ActionAddAll.class:?]
	at minetweaker.runtime.MTTweaker.rollback(MTTweaker.java:88) ~[MTTweaker.class:?]
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:621) ~[MineTweakerImplementationAPI.class:?]
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:83) ~[MineTweakerImplementationAPI$1.class:?]
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:642) ~[MineTweakerImplementationAPI$19.class:?]
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124) ~[MCServer$MCCommand.class:?]"

 However, even after commenting out those newly added lines with // infront of both of them the error still persist.

**Comment by Blue64** [comment]
[ code ] Code Tag [ / code ] works by the way (or ``` ` ` `text` ` ` ```) 
Also, did you forget the ```<>```?
```
ore:ingotYellorium.mirror(ore:ingotUranium);
ore:ingotUranium.addAll(ore:ingotYellorium);
Should be:
<ore:ingotYellorium>.mirror(<ore:ingotUranium>);
<ore:ingotUranium>.addAll(<ore:ingotYellorium>);
```
and I'm not sure, but you may also have those in reverse order. (add, THEN mirror)

**Comment by Blue64** [comment]
That's what I believe is causing your ```ConcurrentModificationException``` as far as I can tell.

**Comment by TerdyTheTerd** [comment]
Ahh thank you, my code in the <> in it, just didn't copy over on to here, and it was the fact that I had .mirror then .addAll instead of the other way, don't know how I missed that, thank you kind sir

**Comment by Blue64** [comment]
Glad to be of help :+1;
