### ISSUE TITLE
java.lang.NoSuchMethodError: net.minecraft.item.crafting.CraftingManager.getInstance()

### ISSUE THREAD

**Issue by matanui159** [stanhebben/MineTweaker3#302]
Ok, first:
1. I know this is a development version. I'm only using this version because one of the mods I'm using (Immersive Engineering) crashes if I use an older version.
2. I know this question has been asked before, but that ultimately ended with "don't use development versions" but as I've explained I'm stuck with the development version unless I get rid of Immersive Engineering (which I like) or MineTweaker (which I want to keep because there are some overpowered recipes in some of the mods I'm using.
3. Yes, I've tested it with the latest version of Forge, with the latest version of MineTweaker with the latest version of Immersive Engineering with no other mods.

Now that's out of the way, I'm getting this error on startup:
```
cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraft.item.crafting.CraftingManager.getInstance()Lnet/minecraft/item/crafting/CraftingManager;
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.crafting.CraftingManager.getInstance()Lnet/minecraft/item/crafting/CraftingManager;
	at minetweaker.mc1710.recipes.MCRecipeManager.<init>(MCRecipeManager.java:41)
	at minetweaker.mc1710.MineTweakerMod.<init>(MineTweakerMod.java:96)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at java.lang.Class.newInstance(Class.java:438)
	at cpw.mods.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:173)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:506)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
```

Can you see if you can fix this please? In the meantime I will look at the mod configs to see if I can either remove the OP items from the mods or disable Immersive Engineering from using MineTweaker.
Thanks in advance.

EDIT: Forgot to point out, I am using 3.0.10B, which is the only version which works with Immersive Engineering

**Comment by jaredlll08** [comment]
No. You DO NOT know what a dev version is.

The development version is for MODDERS, who want to add this mod to their
development environment, from what I can tell, you are neither a modder or
in a development environment.

**Comment by matanui159** [comment]
Oh. sorry didn't exactly fully understand that. (possibly update your website to point out that they are for development environments because I thought they where just the latest unstable version). Still seems a bit weird that when I looked up how to stop Immersive Engineering from crashing when with MineTweaker, they said to get 3.0.10B which only seems to be a development version.

**Comment by jaredlll08** [comment]
I don't control the website unfortunately, also always check curse for versions.

**Comment by Blue64** [comment]
Curse doesn't have the 3.0.10B release if I'm not mistaken, if I recall I had to go to Jenkins or some other popular repository for the 3.0.10B version. 

The crash still hasn't actually been solved as far as I can tell, it's just been pointed out that the Beta Version doesn't equal the Dev Version, so I'd still consider this open unless it's actually been solved.

**Comment by matanui159** [comment]
I had a look and Curse does have 3.0.10B. I'll test it this afternoon as I can't test it now (on iPad).

**Comment by Blue64** [comment]
You said you were already using that version lol

**Comment by matanui159** [comment]
I was using the development version (which as I said, I thought development versions where just the latest, unstable versions). I just switched to 3.0.10B (non development version), and it is definitely working even with Immersive Engineering adding MineTweaker support. So I guess this issue can stay closed.
