### ISSUE TITLE
[bug] Errors with NBT specification (and more)

### ISSUE THREAD

**Issue by DeathHammer000** [stanhebben/MineTweaker3#33]
My script is not working, even though what I have done is in the same format as the wiki.
Here is the erroring part:

val blazeessence = pick.onlyWithTag({display: {Name: "Blaze Essence"}});

The wiki says that this is perfect, but I then get this error when using /minetweaker reload:

2014-08-10 15:52:59 [INFO] [STDERR] java.lang.IllegalArgumentException: value minetweaker.item.IIngredient
2014-08-10 15:52:59 [INFO] [STDERR] at org.objectweb.asm.ClassWriter.a(Unknown Source)
2014-08-10 15:52:59 [INFO] [STDERR] at org.objectweb.asm.MethodWriter.visitLdcInsn(Unknown Source)
2014-08-10 15:52:59 [INFO] [STDERR] at org.objectweb.asm.MethodVisitor.visitLdcInsn(Unknown Source)
2014-08-10 15:52:59 [INFO] [STDERR] at stanhebben.zenscript.util.MethodOutput.constant(MethodOutput.java:79)
2014-08-10 15:52:59 [INFO] [STDERR] at stanhebben.zenscript.type.ZenTypeAny.compileCast(ZenTypeAny.java:201)
2014-08-10 15:52:59 [INFO] [STDERR] at stanhebben.zenscript.expression.ExpressionAs.compile(ExpressionAs.java:33)
2014-08-10 15:52:59 [INFO] [STDERR] at stanhebben.zenscript.expression.ExpressionArray.compile(ExpressionArray.java:64)
2014-08-10 15:52:59 [INFO] [STDERR] at stanhebben.zenscript.expression.ExpressionJavaCallVirtual.compile(ExpressionJavaCallVirtual.java:47)
2014-08-10 15:52:59 [INFO] [STDERR] at stanhebben.zenscript.statements.StatementExpression.compile(StatementExpression.java:21)
2014-08-10 15:52:59 [INFO] [STDERR] at stanhebben.zenscript.ZenModule.compileScripts(ZenModule.java:122)
2014-08-10 15:52:59 [INFO] [STDERR] at minetweaker.runtime.MTTweaker.load(MTTweaker.java:151)
2014-08-10 15:52:59 [INFO] [STDERR] at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:375)
2014-08-10 15:52:59 [INFO] [STDERR] at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:56)
2014-08-10 15:52:59 [INFO] [STDERR] at minetweaker.MineTweakerImplementationAPI$12.execute(MineTweakerImplementationAPI.java:363)
2014-08-10 15:52:59 [INFO] [STDERR] at minetweaker.mc164.server.MCServer$MCCommand.func_71515_b(MCServer.java:117)
2014-08-10 15:52:59 [INFO] [STDERR] at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:88)
2014-08-10 15:52:59 [INFO] [STDERR] at net.minecraft.network.NetServerHandler.func_72566_d(NetServerHandler.java:759)
2014-08-10 15:52:59 [INFO] [STDERR] at net.minecraft.network.NetServerHandler.func_72481_a(NetServerHandler.java:728)
2014-08-10 15:52:59 [INFO] [STDERR] at net.minecraft.network.packet.Packet3Chat.func_73279_a(SourceFile:49)
2014-08-10 15:52:59 [INFO] [STDERR] at net.minecraft.network.MemoryConnection.func_74428_b(MemoryConnection.java:89)
2014-08-10 15:52:59 [INFO] [STDERR] at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:141)
2014-08-10 15:52:59 [INFO] [STDERR] at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
2014-08-10 15:52:59 [INFO] [STDERR] at net.minecraft.server.integrated.IntegratedServerListenThread.func_71747_b(IntegratedServerListenThread.java:109)
2014-08-10 15:52:59 [INFO] [STDERR] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:691)
2014-08-10 15:52:59 [INFO] [STDERR] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
2014-08-10 15:52:59 [INFO] [STDERR] at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:175)
2014-08-10 15:52:59 [INFO] [STDERR] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
2014-08-10 15:52:59 [INFO] [STDERR] at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
2014-08-10 15:52:59 [INFO] [Minecraft-Client] [CHAT] ERROR: recipes.zs - 2:20 > could not find pick
2014-08-10 15:52:59 [INFO] [Minecraft-Client] [CHAT] ERROR: recipes.zs - 2:20 > cannot cast any[any] to any
2014-08-10 15:52:59 [INFO] [Minecraft-Client] [CHAT] ERROR: recipes.zs - 3:20 > could not find pick
2014-08-10 15:52:59 [INFO] [Minecraft-Client] [CHAT] ERROR: recipes.zs - 3:20 > cannot cast any[any] to any
2014-08-10 15:52:59 [INFO] [Minecraft-Client] [CHAT] ERROR: Error executing recipes.zs: value minetweaker.item.IIngredient
2014-08-10 15:52:59 [INFO] [STDOUT] Received script data: 1272 bytes
2014-08-10 15:52:59 [INFO] [Minecraft-Client] [CHAT] Scripts reloaded
2014-08-10 15:54:35 [INFO] [STDOUT] Loading scripts
2014-08-10 15:54:35 [INFO] [STDOUT] MineTweaker: Loading oreDict.zs
2014-08-10 15:54:35 [INFO] [STDOUT] MineTweaker: Loading recipes.zs
2014-08-10 15:54:35 [INFO] [STDERR] java.lang.IllegalArgumentException: value minetweaker.item.IIngredient
2014-08-10 15:54:35 [INFO] [STDERR] at org.objectweb.asm.ClassWriter.a(Unknown Source)
2014-08-10 15:54:35 [INFO] [STDERR] at org.objectweb.asm.MethodWriter.visitLdcInsn(Unknown Source)
2014-08-10 15:54:35 [INFO] [STDERR] at org.objectweb.asm.MethodVisitor.visitLdcInsn(Unknown Source)
2014-08-10 15:54:35 [INFO] [STDERR] at stanhebben.zenscript.util.MethodOutput.constant(MethodOutput.java:79)
2014-08-10 15:54:35 [INFO] [STDERR] at stanhebben.zenscript.type.ZenTypeAny.compileCast(ZenTypeAny.java:201)
2014-08-10 15:54:35 [INFO] [STDERR] at stanhebben.zenscript.expression.ExpressionAs.compile(ExpressionAs.java:33)
2014-08-10 15:54:35 [INFO] [STDERR] at stanhebben.zenscript.expression.ExpressionArray.compile(ExpressionArray.java:64)
2014-08-10 15:54:35 [INFO] [STDERR] at stanhebben.zenscript.expression.ExpressionJavaCallVirtual.compile(ExpressionJavaCallVirtual.java:47)
2014-08-10 15:54:35 [INFO] [STDERR] at stanhebben.zenscript.statements.StatementExpression.compile(StatementExpression.java:21)
2014-08-10 15:54:35 [INFO] [STDERR] at stanhebben.zenscript.ZenModule.compileScripts(ZenModule.java:122)
2014-08-10 15:54:35 [INFO] [STDERR] at minetweaker.runtime.MTTweaker.load(MTTweaker.java:151)
2014-08-10 15:54:35 [INFO] [STDERR] at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:375)
2014-08-10 15:54:35 [INFO] [STDERR] at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:56)
2014-08-10 15:54:35 [INFO] [STDERR] at minetweaker.MineTweakerImplementationAPI$12.execute(MineTweakerImplementationAPI.java:363)
2014-08-10 15:54:35 [INFO] [STDERR] at minetweaker.mc164.server.MCServer$MCCommand.func_71515_b(MCServer.java:117)
2014-08-10 15:54:35 [INFO] [STDERR] at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:88)
2014-08-10 15:54:35 [INFO] [STDERR] at net.minecraft.network.NetServerHandler.func_72566_d(NetServerHandler.java:759)
2014-08-10 15:54:35 [INFO] [STDERR] at net.minecraft.network.NetServerHandler.func_72481_a(NetServerHandler.java:728)
2014-08-10 15:54:35 [INFO] [STDERR] at net.minecraft.network.packet.Packet3Chat.func_73279_a(SourceFile:49)
2014-08-10 15:54:35 [INFO] [STDERR] at net.minecraft.network.MemoryConnection.func_74428_b(MemoryConnection.java:89)
2014-08-10 15:54:35 [INFO] [STDERR] at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:141)
2014-08-10 15:54:35 [INFO] [STDERR] at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
2014-08-10 15:54:35 [INFO] [STDERR] at net.minecraft.server.integrated.IntegratedServerListenThread.func_71747_b(IntegratedServerListenThread.java:109)
2014-08-10 15:54:35 [INFO] [STDERR] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:691)
2014-08-10 15:54:35 [INFO] [STDERR] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
2014-08-10 15:54:35 [INFO] [STDERR] at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:175)
2014-08-10 15:54:35 [INFO] [STDERR] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
2014-08-10 15:54:35 [INFO] [STDERR] at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
2014-08-10 15:54:35 [INFO] [Minecraft-Client] [CHAT] ERROR: recipes.zs - 2:20 > could not find pick
2014-08-10 15:54:35 [INFO] [Minecraft-Client] [CHAT] ERROR: recipes.zs - 2:20 > cannot cast any[any] to any
2014-08-10 15:54:35 [INFO] [Minecraft-Client] [CHAT] ERROR: recipes.zs - 3:20 > could not find pick
2014-08-10 15:54:35 [INFO] [Minecraft-Client] [CHAT] ERROR: recipes.zs - 3:20 > cannot cast any[any] to any
2014-08-10 15:54:35 [INFO] [Minecraft-Client] [CHAT] ERROR: Error executing recipes.zs: value minetweaker.item.IIngredient

I've also noticed that OreDict names do not update when using /minetweaker reload (I use NEI and NEI Plugins to view them).

--EDIT--

Found this error. Part of my script:

recipes.addShaped(<item.unmatter>, [[<item.extrautils:unstableingot:1>, <item.extrautils:unstableingot:1>, <item.extrautils:unstableingot:1>], [<item.extrautils:unstableingot:1>, <tile.stone>, <item.extrautils:unstableingot:1>], [<item.extrautils:unstableingot:1>, <item.extrautils:unstableingot:1>, <item.extrautils:unstableingot:1>]]);

The error: ERROR: Error parsing recipes.zs:12 -- ) expected

If I move the text, the error stays on the same line - even with a different method. The error in the script itself was in a different line altogether.

--EDIT--

And now this: "] or , expected" when this is the affected line:

recipes.addShaped(<item.ThaumcraftExtras:darkthaumium>, [[<item.factorization:dark_iron_ingot>, <item.factorization:dark_iron_ingot>, <item.factorization:dark_iron_ingot>], [item.factorization:dark_iron_ingot>, <item.ItemResource:2>, <item.factorization:dark_iron_ingot>], [<item.factorization:dark_iron_ingot>, <item.factorization:dark_iron_ingot>, <item.factorization:dark_iron_ingot>]]);

**Comment by jaredlll08** [comment]
This seems like user error, also @DeathHammer000  in your scripts, what is "pick"?
