### ISSUE TITLE
Set&get NBT

### ISSUE THREAD

**Issue by Sasszem** [stanhebben/MineTweaker3#335]
I've read the tutorial on function recipes(or whatever is their name) and I've wanted to do the same thing with ImmersiveEngineering's hammer.  Sadly, IE's hammer stores damage data in it's NBT. I can easily set it, but I can not retrieve the tag it contains.
`print(input.hammer.tag);` fails for some reason, but I found In `api/item/IItemStack.java` this:

``` java
/**
     * Gets the item tag. (NBT data) The resulting data is immutable and can
     * only be changed with updateTag. Returns empty data if there is no data.
     * Never returns null.
     * 
     * @return item tag
     */
    @ZenGetter("tag")
    public IData getTag();
`
So there sholud not be a problem.

To repair the hammer at crafting, We need to modify It's `hammedDmg` tag, but **I can't get its NBT, & even If I get it, It would be immutable.** So We can not crate recipes to dynamically modify Item's NBTs. That should be a good feature.
```

**Comment by Sil3ntStorm** [comment]
You should be able to get the value with `inputs.hammer.tag.hammedDmg;` . See also the discussion in #329

**Comment by Sasszem** [comment]
I've used the following code:

``` javascript
recipes.addShapeless(<ImmersiveEngineering:tool>, [<ImmersiveEngineering:tool>.marked("hammer").noReturn(), <ore:ingotIron>],
 function(output, inputs, crafting) {

  return inputs.hammer.withTag({hammerDmg:max(0, (inputs.hammer.tag.hammerDmg) - 25)});
});
```

But I've got the following crash:

```
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2016.04.01. 22:09
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
    at minetweaker.mc1710.data.NBTConverter.from(NBTConverter.java:49)
    at minetweaker.mc1710.data.NBTConverter.fromMap(NBTConverter.java:157)
    at minetweaker.mc1710.data.NBTConverter.fromMap(NBTConverter.java:45)
    at minetweaker.api.data.DataMap.convert(DataMap.java:283)
    at minetweaker.mc1710.data.NBTConverter.from(NBTConverter.java:49)
    at minetweaker.mc1710.item.MCItemStack.withTag(MCItemStack.java:205)
    at ZenClass0.process(Unknown Source)
    at minetweaker.api.recipes.ShapelessRecipe.getCraftingResult(ShapelessRecipe.java:60)
    at minetweaker.mc1710.recipes.ShapelessRecipeOre.func_77572_b(ShapelessRecipeOre.java:36)
    at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:325)
    at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:80)
    at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:81)
    at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:222)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
    at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
    at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
    at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
    at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
    at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
    at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:607)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at minetweaker.mc1710.data.NBTConverter.from(NBTConverter.java:49)
    at minetweaker.mc1710.data.NBTConverter.fromMap(NBTConverter.java:157)
    at minetweaker.mc1710.data.NBTConverter.fromMap(NBTConverter.java:45)
    at minetweaker.api.data.DataMap.convert(DataMap.java:283)
    at minetweaker.mc1710.data.NBTConverter.from(NBTConverter.java:49)
    at minetweaker.mc1710.item.MCItemStack.withTag(MCItemStack.java:205)
    at ZenClass0.process(Unknown Source)
    at minetweaker.api.recipes.ShapelessRecipe.getCraftingResult(ShapelessRecipe.java:60)
    at minetweaker.mc1710.recipes.ShapelessRecipeOre.func_77572_b(ShapelessRecipeOre.java:36)
    at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:325)
    at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:80)
    at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:81)
    at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:222)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
    at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
    at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
    at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
    at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
    at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
    at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:607)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiInventory

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Sasszem'/499, l='MpServer', x=915,97, y=31,62, z=-333,12]]
    Chunk stats: MultiplayerChunkCache: 169, 178
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (935,4,-345), Chunk: (at 7,0,7 in 58,-22; contains blocks 928,0,-352 to 943,255,-337), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
    Level time: 746549 game time, 827297 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 36 total; [EntityCow['Cow'/11, l='MpServer', x=840,25, y=30,00, z=-375,69], EntityCow['Cow'/20, l='MpServer', x=915,03, y=30,00, z=-417,25], EntityCow['Cow'/21, l='MpServer', x=921,50, y=30,00, z=-416,50], EntityCow['Cow'/23, l='MpServer', x=918,31, y=30,00, z=-413,09], EntityStorm['entity.minegicka3_Storm.name'/24, l='MpServer', x=938,69, y=33,78, z=-341,91], EntityStorm['entity.minegicka3_Storm.name'/25, l='MpServer', x=938,31, y=33,78, z=-340,91], EntityStorm['entity.minegicka3_Storm.name'/26, l='MpServer', x=937,66, y=33,78, z=-340,03], EntityStorm['entity.minegicka3_Storm.name'/27, l='MpServer', x=936,81, y=33,78, z=-339,38], EntityStorm['entity.minegicka3_Storm.name'/28, l='MpServer', x=935,81, y=33,78, z=-338,94], EntityStorm['entity.minegicka3_Storm.name'/29, l='MpServer', x=934,75, y=33,78, z=-338,78], EntityStorm['entity.minegicka3_Storm.name'/30, l='MpServer', x=940,34, y=33,78, z=-332,69], EntityStorm['entity.minegicka3_Storm.name'/31, l='MpServer', x=939,06, y=33,78, z=-332,50], EntityStorm['entity.minegicka3_Storm.name'/32, l='MpServer', x=937,75, y=33,78, z=-332,63], EntityStorm['entity.minegicka3_Storm.name'/33, l='MpServer', x=936,53, y=33,78, z=-333,06], EntityStorm['entity.minegicka3_Storm.name'/34, l='MpServer', x=935,47, y=33,78, z=-333,84], EntityStorm['entity.minegicka3_Storm.name'/35, l='MpServer', x=934,66, y=33,78, z=-334,84], EntityStorm['entity.minegicka3_Storm.name'/36, l='MpServer', x=935,31, y=34,53, z=-330,91], EntityStorm['entity.minegicka3_Storm.name'/37, l='MpServer', x=934,16, y=34,53, z=-330,53], EntityStorm['entity.minegicka3_Storm.name'/38, l='MpServer', x=932,94, y=34,53, z=-330,41], EntityStorm['entity.minegicka3_Storm.name'/39, l='MpServer', x=931,72, y=34,53, z=-330,56], EntityStorm['entity.minegicka3_Storm.name'/40, l='MpServer', x=930,56, y=34,53, z=-331,00], EntityStorm['entity.minegicka3_Storm.name'/41, l='MpServer', x=929,53, y=34,53, z=-331,66], EntityStorm['entity.minegicka3_Storm.name'/42, l='MpServer', x=928,66, y=34,53, z=-332,56], EntityStorm['entity.minegicka3_Storm.name'/43, l='MpServer', x=942,19, y=33,78, z=-315,94], EntityStorm['entity.minegicka3_Storm.name'/44, l='MpServer', x=942,94, y=33,78, z=-314,97], EntityStorm['entity.minegicka3_Storm.name'/45, l='MpServer', x=943,41, y=33,78, z=-313,81], EntityStorm['entity.minegicka3_Storm.name'/46, l='MpServer', x=943,53, y=33,78, z=-312,59], EntityStorm['entity.minegicka3_Storm.name'/47, l='MpServer', x=943,38, y=33,78, z=-311,38], EntityStorm['entity.minegicka3_Storm.name'/48, l='MpServer', x=942,88, y=33,78, z=-310,25], EntitySheep['Sheep'/50, l='MpServer', x=954,41, y=30,00, z=-407,75], EntitySheep['Sheep'/51, l='MpServer', x=955,50, y=30,00, z=-396,50], EntitySheep['Sheep'/52, l='MpServer', x=943,91, y=30,00, z=-394,13], EntitySheep['Sheep'/60, l='MpServer', x=960,06, y=30,00, z=-396,03], EntityChicken['Chicken'/61, l='MpServer', x=990,38, y=30,00, z=-276,56], EntityChicken['Chicken'/62, l='MpServer', x=988,41, y=30,00, z=-277,38], EntityClientPlayerMP['Sasszem'/499, l='MpServer', x=915,97, y=31,62, z=-333,12]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_66, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 309153168 bytes (294 MB) / 1195900928 bytes (1140 MB) up to 2386558976 bytes (2276 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2560m -XX:MaxPermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: Minecraft 1.7.10 MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1517 Optifine OptiFine_1.7.10_HD_U_C1 48 mods loaded, 48 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader] (modpack.jar) 
    UCHIJAAAA   Forge{10.13.4.1517} [Minecraft Forge] (modpack.jar) 
    UCHIJAAAA   appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
    UCHIJAAAA   CustomLanPort{0.0.1} [CustomLanPort] (minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
    UCHIJAAAA   bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
    UCHIJAAAA   Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
    UCHIJAAAA   AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
    UCHIJAAAA   appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
    UCHIJAAAA   ATG{0.10.0} [Alternate Terrain Generation] (ATG-1.7.10-0.12.0.jar) 
    UCHIJAAAA   BiblioCraft{1.11.2} [BiblioCraft] (BiblioCraft[v1.11.2][MC1.7.10].jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) 
    UCHIJAAAA   BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
    UCHIJAAAA   chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) 
    UCHIJAAAA   eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCHIJAAAA   EnderStorage{1.4.7.38} [EnderStorage] (EnderStorage-1.7.10-1.4.7.38-universal.jar) 
    UCHIJAAAA   ImmersiveEngineering{0.7.4} [Immersive Engineering] (ImmersiveEngineering-0.7.4.jar) 
    UCHIJAAAA   KeepingInventory{1.5} [Keeping Inventory] (KeepingInventory-1.7.10-1.5.jar) 
    UCHIJAAAA   ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   Magneticraft{0.6.0-final} [Magneticraft] (magneticraft-0.6.1-final.jar) 
    UCHIJAAAA   malisiscore{1.7.10-0.12.8} [MalisisCore] (malisiscore-1.7.10-0.12.8.jar) 
    UCHIJAAAA   malisisdoors{1.7.10-1.9.4} [Malisis' Doors] (malisisdoors-1.7.10-1.9.4.jar) 
    UCHIJAAAA   MapWriter{2.1.2} [MapWriter] (MapWriter-Mod-1.7.10.jar) 
    UCHIJAAAA   minegicka3{1.0.0} [Minegicka 3] (minegicka3-1.7.10-1.0.0.jar) 
    UCHIJAAAA   MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
    UCHIJAAAA   ProjectE{1.7.10-PE1.7.3} [ProjectE] (ProjectE-1.7.10-PE1.7.3.jar) 
    UCHIJAAAA   MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar) 
    UCHIJAAAA   ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
    UCHIJAAAA   ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
    UCHIJAAAA   ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
    UCHIJAAAA   ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
    UCHIJAAAA   ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
    UCHIJAAAA   ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
    UCHIJAAAA   ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
    UCHIJAAAA   ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
    UCHIJAAAA   ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
    UCHIJAAAA   Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
    UCHIJAAAA   SSTOW{1.7.10-0.1-RC9-7} [Soul Shards: The Old Ways] (SoulShards-TOW-1.7.10-0.1-RC9-7.jar) 
    UCHIJAAAA   StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.5} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.5.jar) 
    UCHIJAAAA   McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
    UCHIJAAAA   MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
    UCHIJAAAA   RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
    UCHIJAAAA   ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    GL info: ' Vendor: 'Intel' Version: '4.2.0 - Build 10.18.10.3540' Renderer: 'Intel(R) HD Graphics'
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.0.2-262
    AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Launched Version: 1.7.10-Forge10.13.4.1517-1.7.10
    XRay Version: 4.1.7
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics GL version 4.2.0 - Build 10.18.10.3540, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: [Sphax_NEI_512x-64x.zip, Sphax_ProjectRed_64x.zip]
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)
```

This report is Chinese to me. I know that It mentioned MineTweaker & NEI.

**Comment by jaredlll08** [comment]
The error means that the hammer does not have a tag (possible with a not damaged hammer)

**Comment by Blue64** [comment]
so, if I've got this correct, the crash came from
```
recipes.addShapeless(<ImmersiveEngineering:tool>, [<ImmersiveEngineering:tool>.marked("hammer").noReturn(), <ore:ingotIron>],
 function(output, inputs, crafting) {

  return inputs.hammer.withTag({hammerDmg:max(0, (inputs.hammer.tag.hammerDmg) - 25)});
});
```
but can be fixed with
```
recipes.addShapeless(<ImmersiveEngineering:tool>.withTag({hammerDmg:max(0, (inputs.hammer.tag.hammerDmg) - 25)}), [<ImmersiveEngineering:tool>.withTag({hammerDmg:}), <ore:ingotIron>],
```
...right?
