### ISSUE TITLE
java.lang.NoClassDefFoundError: minetweaker/api/item/IItemStackAny

### ISSUE THREAD

**Issue by ghost** [stanhebben/MineTweaker3#337]
MineTweaker 3.0.10B for 1.7.10

I've tried `as IItemStack, IItemStackAny, IIngredient`

Script:

```
var toRemove = [
    <TConstruct:ToolForgeBlock:*>,
    <TConstruct:CraftingSlab:5>
] as IItemStack[];

for item in toRemove {
    recipes.remove(item);
}
```

Error:

```
ERROR: Error executing tekkify.zs: minetweaker/api/item/IItemStackAny
java.lang.NoClassDefFoundError: minetweaker/api/item/IItemStackAny
    at Tekkify.__script__(tekkify.zs:1)
    at __ZenMain__.run(tekkify.zs)
    at minetweaker.runtime.MTTweaker.load(MTTweaker.java:163)
    at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:656)
    at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:83)
    at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:642)
    at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
    at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
    at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: minetweaker.api.item.IItemStackAny
    at java.lang.ClassLoader.findClass(Unknown Source)
    at stanhebben.zenscript.ZenModule$MyClassLoader.findClass(ZenModule.java:350)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 19 more
```

**Comment by ghost** [comment]
Using the line

```
var myItems = [<minecraft:diamond_pickaxe>, <minecraft:iron_pickaxe>] as IItemStack[];
```

also produces the same error.

**Comment by Voidi** [comment]
Have you this `import minetweaker.item.IItemStack;` in your Script?
http://minetweaker3.powerofbytes.com/wiki/Tutorial:Control_Structures

**Comment by ghost** [comment]
I completely forgot about this! I'll try tomorrow.
Have you this `import minetweaker.item.IItemStack;` in your Script?
http://minetweaker3.powerofbytes.com/wiki/Tutorial:Control_Structures

---

**Comment by ghost** [comment]
Working now, thanks!
