### ISSUE TITLE
null error ?

### ISSUE THREAD

**Issue by mightydanp** [stanhebben/MineTweaker3#377]
for some reason i cannot make this recipe
print("Extreme Wrench") ;
recipes.remove(bigreactors:Wrench);
recipes.addShaped(bigreactors:Wrench, [
  [null, plateSteel, null],
  [wool, plateSteel, plateSteel],
  [plateSteel, wool, null]
]);

it says

ERROR: ExtremeReactors.zs:91: Could not resolve <bigreactors : Wrench>
ERROR: ExtremeReactors.zs:92: Could not resolve <bigreactors : Wrench>
INFO: Removing 3 furnace recipes
INFO: Removing 0 recipes
INFO: Turbine Housing Core
ERROR: Error executing ExtremeReactors.zs: null
java.lang.NullPointerException
    at minetweaker.mc1102.recipes.MCRecipeManager.remove(MCRecipeManager.java:106)
    at ExtremeReactors.**script**(ExtremeReactors.zs:27)
    at **ZenMain**.run(ExtremeReactors.zs)
    at minetweaker.runtime.MTTweaker.load(MTTweaker.java:161)
    at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:682)
    at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:75)
    at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:667)
    at minetweaker.mc1102.server.MCServer$MCCommand.func_184881_a(MCServer.java:122)
    at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104)
    at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83)
    at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913)
    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892)
    at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
    at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.func_181617_a(SourceFile:45)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

**Comment by jaredlll08** [comment]
Full script?

**Comment by mightydanp** [comment]
// BigReactors.zs tweaks

val dustRedstone = ore:dustRedstone;
val plateSteel = ore:plateSteel;
val plateGold = ore:plateGold;
val ingotGold = ore:ingotGold;
val ingotSteel = ore:ingotSteel;
val stickSteel = ore:stickSteel;
val barsIron = ore:barsIron;
val ingotGraphite = ore:ingotGraphite;
val ingotYellorium = ore:ingotYellorium;
val blockYellowrium = ore:blockYellorium;
val ingotCyanite = ore:ingotCyanite;
val glassTurbine = bigreactors:turbineGlass;
val reactorCasingCore = bigreactors:reactorCasingCores;
val turbineCasingCore = bigreactors:turbineHousingCores;
val hardenedGlass = ore:blockGlassHardened;
val reactorCasing = bigreactors:reactorCasing;
val turbineCasing = bigreactors:turbineHousing;
val redstoneComparator = minecraft:comparator;
val wool = minecraft:wool;

furnace.remove(ingotGraphite); // Improper duplicate of Gregtech smelting ore
recipes.remove(ingotGraphite); // Nerf to machining requirement

print("Turbine Housing Core") ;
recipes.remove(bigreactors:turbineCasingCores);
recipes.addShaped(bigreactors:turbineCasingCores, [
  [plateSteel, ingotGraphite, plateSteel],
  [ingotGold, redstoneComparator, ingotGold],
  [plateSteel, ingotGraphite, plateSteel]
]);

print("Turbine Housing");
recipes.remove(bigreactors:turbineHousing);
recipes.addShaped(bigreactors:turbineHousing \* 4, [
  [plateSteel, ingotGraphite, plateSteel],
  [plateSteel, turbineCasingCore, plateSteel],
  [plateSteel, ingotGraphite, plateSteel]
]);

print("Turbine Glass");
recipes.remove(bigreactors:turbineGlass);
recipes.addShaped(bigreactors:turbineGlass \* 1, [
  [hardenedGlass, turbineCasing, hardenedGlass]
]);

print("Reactor Housing Core");
recipes.remove(bigreactors:reactorCasingCores);
recipes.addShaped(bigreactors:reactorCasingCores \* 1, [
  [plateSteel, ingotGraphite, plateSteel],
  [ingotGold, dustRedstone, ingotGold],
  [plateSteel, ingotGraphite, plateSteel]
]);

print("Reactor Housing") ;
recipes.remove(bigreactors:reactorCasing);
recipes.addShaped(bigreactors:reactorCasing\* 4, [
  [plateSteel, ingotGraphite, plateSteel],
  [plateSteel, ingotYellorium, plateSteel],
  [plateSteel, ingotGraphite, plateSteel]
]);

print("Reactor Glass");
recipes.remove(bigreactors:reactorGlass);
recipes.addShaped(bigreactors:reactorGlass \* 1, [
  [hardenedGlass, reactorCasing, hardenedGlass]
]);

print("Fuel Rod") ;
recipes.remove(bigreactors:reactorFuelRod);
recipes.addShaped(bigreactors:reactorFuelRod, [
  [plateSteel, ingotYellorium, plateSteel],
  [glassTurbine, blockYellowrium, glassTurbine],
  [plateSteel, ingotYellorium, plateSteel]
]);

print("Turbine Rotor Shaft") ;
recipes.remove(bigreactors:turbineRotorShaft);
recipes.addShaped(bigreactors:turbineRotorShaft, [
    [plateSteel, ingotCyanite, plateSteel]
]);

print("Turbine Rotor Blade") ;
recipes.remove(bigreactors:turbineRotorBlade);
recipes.addShaped(bigreactors:turbineRotorBlade, [
    [ingotCyanite, plateSteel, plateSteel]
]);

print("Extreme Wrench") ;
recipes.remove(bigreactors:Wrench);
recipes.addShaped(bigreactors:Wrench, [
  [null, plateSteel, null],
  [wool, plateSteel, plateSteel],
  [plateSteel, wool, null]
]);

**Comment by mightydanp** [comment]
i am using craft tweaker 1.10.2 latest

**Comment by jaredlll08** [comment]
Please upload your script to pastebin or similar, as github strips the
formatting
