### ISSUE TITLE
character ‘ can cause error?

### ISSUE THREAD

**Issue by NamelessPoem** [stanhebben/MineTweaker3#382]
**I wrote a script like this:
`recipes.remove(<THKaguyaMod:Sorcerer's Sutra Scroll>);`
but it dosn't work.
I tried some other item in the same mod without the ‘,then it works fine.
Minecraft Version:1.7.10
Mod Version:3.0.10
The error report:**
`ERROR: Error loading \scripts\Crafting.zs: stanhebben.zenscript.parser.TokenException: Invalid character at \scripts\Crafting.zs:90 - ?
stanhebben.zenscript.parser.TokenException: Invalid character at \scripts\Crafting.zs:90 - ?
        at stanhebben.zenscript.parser.TokenStream.advanceToken(TokenStream.java:234)
        at stanhebben.zenscript.parser.TokenStream.advance(TokenStream.java:198)
        at stanhebben.zenscript.parser.TokenStream.next(TokenStream.java:166)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readPrimaryExpression(ParsedExpression.java:374)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readPostfixExpression(ParsedExpression.java:265)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readUnaryExpression(ParsedExpression.java:260)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readMulExpression(ParsedExpression.java:225)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readAddExpression(ParsedExpression.java:205)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readCompareExpression(ParsedExpression.java:161)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readAndExpression(ParsedExpression.java:151)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readXorExpression(ParsedExpression.java:141)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readOrExpression(ParsedExpression.java:131)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readAndAndExpression(ParsedExpression.java:121)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readOrOrExpression(ParsedExpression.java:111)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readConditionalExpression(ParsedExpression.java:98)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readAssignExpression(ParsedExpression.java:53)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readPostfixExpression(ParsedExpression.java:292)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readUnaryExpression(ParsedExpression.java:260)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readMulExpression(ParsedExpression.java:225)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readAddExpression(ParsedExpression.java:205)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readCompareExpression(ParsedExpression.java:161)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readAndExpression(ParsedExpression.java:151)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readXorExpression(ParsedExpression.java:141)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readOrExpression(ParsedExpression.java:131)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readAndAndExpression(ParsedExpression.java:121)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readOrOrExpression(ParsedExpression.java:111)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readConditionalExpression(ParsedExpression.java:98)
        at stanhebben.zenscript.parser.expression.ParsedExpression.readAssignExpression(ParsedExpression.java:53)
        at stanhebben.zenscript.parser.expression.ParsedExpression.read(ParsedExpression.java:40)
        at stanhebben.zenscript.statements.Statement.read(Statement.java:90)
        at stanhebben.zenscript.ZenParsedFile.<init>(ZenParsedFile.java:129)
        at minetweaker.runtime.MTTweaker.load(MTTweaker.java:137)
        at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:656)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.doubledoordev.mtrm.network.MessageSend.makeScript(MessageSend.java:193)
        at net.doubledoordev.mtrm.network.MessageSend.access$000(MessageSend.java:21)
        at net.doubledoordev.mtrm.network.MessageSend$Handler.onMessage(MessageSend.java:213)
        at net.doubledoordev.mtrm.network.MessageSend$Handler.onMessage(MessageSend.java:208)
        at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37)
        at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
        at fastcraft.at.a(F:978)
        at fastcraft.H.aq(F:36)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)`
# Well, I admit it's rare that an item name with ' ....But I hope this problem can be solved.

**Comment by jaredlll08** [comment]
Can't be solved, an item should NEVER have any punctuation, will NOT be fixed.
