### ISSUE TITLE
Unable to reload scripts

### ISSUE THREAD

**Issue by Shahelion** [stanhebben/MineTweaker3#392]
"An unknown error occurred while attempting to perform this command"

Console:

[22:22:12] [Server thread/ERROR]: Couldn't process command: 'mt reload'
java.lang.NullPointerException
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:143) ~[MTTweaker.class:?]
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:656) ~[MineTweakerImplementationAPI.class:?]
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:83) ~[MineTweakerImplementationAPI$1.class:?]
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:642) ~[MineTweakerImplementationAPI$19.class:?]
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124) ~[MCServer$MCCommand.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at fastcraft.at.a(F:978) [%5BClient%5D%20Fastcraft%201.23.jar:?]
	at fastcraft.H.aq(F:36) [%5BClient%5D%20Fastcraft%201.23.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[22:22:12] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command

**Comment by jaredlll08** [comment]
1.7 is no longer supported. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately
