### ISSUE TITLE
Fatal error on script reload

### ISSUE THREAD

**Issue by Gunner76th** [stanhebben/MineTweaker3#415]
Every once in awhile, I get a Fatal Error and disconnected from the server when I do /mt reload.  It seems to happen mostly when there is an error in my script, however I have had it happen when there wasn't one as well, however subsequent reloads did not cause the error. 

Here is the client console output at the time of the reload when the DC occurs. There is no crash as it simply displays the standard "A fatal error has occured, this connection is terminated" screen. 
http://pastebin.com/0BwWMv7R

In addition here is the corresponding server console output for this same event. http://pastebin.com/kUpu602E

**Comment by jaredlll08** [comment]
Immersiveengineering issue.

**Comment by Gunner76th** [comment]
I am confused as to how it is and IE issue, when I have not changed any recipes that would affect their items

**Comment by Gunner76th** [comment]
Regardless, I am forwarding this error to them

**Comment by Blue64** [comment]
this is how you can tell:
```
[B#349]     at blusunrize.lib.manual.ManualPages$Crafting.recalculateCraftingRecipes(ManualPages.java:428) ~[ManualPages$Crafting.class:?]
[B#349]     at blusunrize.lib.manual.ManualPages$Crafting.<init>(ManualPages.java:420) ~[ManualPages$Crafting.class:?]
[B#349]     at blusunrize.immersiveengineering.client.ClientProxy.handleMineralManual(ClientProxy.java:820) ~[ClientProxy.class:?]
[B#349]     at blusunrize.immersiveengineering.common.util.network.MessageMineralListSync$Handler.onMessage(MessageMineralListSync.java:61) ~[MessageMineralListSync$Handler.class:?]
[B#349]     at blusunrize.immersiveengineering.common.util.network.MessageMineralListSync$Handler.onMessage(MessageMineralListSync.java:53) ~[MessageMineralListSync$Handler.class:?]
```
`blusunrize` is the User, `immersiveengineering` is the Mod. `blusunrize.immersiveengineering.` is the most recent reference in the `Stack Trace`, which _USUALLY_ means that they're the ones you need to talk to.

Another dead giveaway:
```
[B#349]  [11:22:56] [Netty Client IO #1/ERROR] [FML]: There was a critical exception handling a packet on channel immersiveengineering
[B#349]  java.util.ConcurrentModificationException
[B#349]     at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_121]
[B#349]     at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_121]
[B#349]     at blusunrize.lib.manual.ManualPages$Crafting.recalculateCraftingRecipes(ManualPages.java:428) ~[ManualPages$Crafting.class:?]
[B#349]     at blusunrize.lib.manual.ManualPages$Crafting.<init>(ManualPages.java:420) ~[ManualPages$Crafting.class:?]
[B#349]     at blusunrize.immersiveengineering.client.ClientProxy.handleMineralManual(ClientProxy.java:820) ~[ClientProxy.class:?]
[B#349]     at blusunrize.immersiveengineering.common.util.network.MessageMineralListSync$Handler.onMessage(MessageMineralListSync.java:61) ~[MessageMineralListSync$Handler.class:?]
[B#349]     at blusunrize.immersiveengineering.common.util.network.MessageMineralListSync$Handler.onMessage(MessageMineralListSync.java:53) ~[MessageMineralListSync$Handler.class:?]
```
It's something that is involved with the Mineral List Sync (and potentially the Mineral List)
```
[B#349]     at blusunrize.immersiveengineering.common.util.network.MessageMineralListSync$Handler.onMessage(MessageMineralListSync.java:53) ~[MessageMineralListSync$Handler.class:?]
```
Mineral Manual
```
[B#349]     at blusunrize.immersiveengineering.client.ClientProxy.handleMineralManual(ClientProxy.java:820) ~[ClientProxy.class:?]
```
and Crafting Recipes
```
[B#349]     at blusunrize.lib.manual.ManualPages$Crafting.recalculateCraftingRecipes(ManualPages.java:428) ~[ManualPages$Crafting.class:?]
```
you just gotta know how to read the code.

Edit: Merged Posts:

on a related note, this issue might have already been resolved by a [similar Bug Report](https://github.com/BluSunrize/ImmersiveEngineering/issues/730)

**Comment by Blue64** [comment]
on a related note, this issue might have already been resolved by a [similar Bug Report](https://github.com/BluSunrize/ImmersiveEngineering/issues/730)
