### ISSUE TITLE
is it mod tweaker that stops the server startup ????

### ISSUE THREAD

**Issue by PSILONCRAFT** [stanhebben/MineTweaker3#429]
09.05 08:53:33 [Multicraft] Loaded config for "Mod: FTB (Kontakt support)"
09.05 08:53:33 [Multicraft] Starting server!
09.05 08:53:33 [Multicraft] Loading server properties
09.05 08:53:32 [Multicraft] Server stopped
09.05 08:53:32 [Multicraft] Retrying server startup
09.05 08:53:27 [Multicraft] Server stopped
09.05 08:53:27 [Multicraft] Server shut down
09.05 08:53:27 [Multicraft] Error writing to server: [Errno 22] Invalid argument
09.05 08:53:27 [Multicraft] Error writing to server: [Errno 22] Invalid argument
09.05 08:53:27 [Multicraft] Stopping server!
09.05 08:53:27 [Multicraft] Server shut down
09.05 08:53:27 [Multicraft] Error writing to server: [Errno 22] Invalid argument
09.05 08:53:27 [Multicraft] Error writing to server: [Errno 22] Invalid argument
09.05 08:53:27 [Multicraft] Stopping server!
09.05 08:53:27 [Multicraft] Server shut down
09.05 08:53:27 [Multicraft] Error writing to server: [Errno 22] Invalid argument
09.05 08:53:27 [Multicraft] Error writing to server: [Errno 22] Invalid argument
09.05 08:53:27 [Multicraft] Stopping server!
09.05 08:53:27 [Multicraft] Server shut down
09.05 08:53:27 [Multicraft] Error writing to server: [Errno 22] Invalid argument
09.05 08:53:27 [Multicraft] Error writing to server: [Errno 22] Invalid argument
09.05 08:53:27 [Multicraft] Stopping server!
09.05 08:53:27 [Multicraft] Server shut down
09.05 08:53:27 [Multicraft] Error writing to server: [Errno 22] Invalid argument
09.05 08:53:27 [Multicraft] Error writing to server: [Errno 22] Invalid argument
09.05 08:53:27 [Multicraft] Stopping server!
09.05 08:53:27 [Multicraft] Server shut down
09.05 08:53:27 [Server] INFO Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=512m; support was removed in 8.0
09.05 08:53:25 [Multicraft] Skipped 50 lines due to rate limit (30/s)
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeminetweaker.mc1102.recipes.ShapedRecipeOre@4658dac0
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeminetweaker.mc1102.recipes.ShapedRecipeOre@4e159406
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeminetweaker.mc1102.recipes.ShapedRecipeOre@6214633a
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeminetweaker.mc1102.recipes.ShapedRecipeOre@35a126c
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeminetweaker.mc1102.recipes.ShapedRecipeOre@71e4d85b
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeminetweaker.mc1102.recipes.ShapedRecipeOre@2b0567f2
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeminetweaker.mc1102.recipes.ShapedRecipeOre@f29395d
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeminetweaker.mc1102.recipes.ShapedRecipeOre@9154f4c
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeminetweaker.mc1102.recipes.ShapedRecipeOre@57d0ea3d
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeminetweaker.mc1102.recipes.ShapedRecipeOre@1ddf3e9
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeminetweaker.mc1102.recipes.ShapedRecipeOre@6e126418
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeminetweaker.mc1102.recipes.ShapedRecipeOre@2fbe5085
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeminetweaker.mc1102.recipes.ShapedRecipeOre@73941e62
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeminetweaker.mc1102.recipes.ShapedRecipeOre@7abad2ea
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:addRecipe:9]: adding recipe net.minecraft.item.crafting.ShapelessRecipes@1f7a8256
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:addRecipe:9]: adding recipe net.minecraft.item.crafting.ShapelessRecipes@3058eb4f
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:addRecipe:9]: adding recipe net.minecraft.item.crafting.ShapelessRecipes@6664a4c8
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:addRecipe:9]: adding recipe net.minecraft.item.crafting.ShapelessRecipes@5a6d3e1c
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:addRecipe:9]: adding recipe net.minecraft.item.crafting.ShapelessRecipes@11ce6f35
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:addRecipe:9]: adding recipe net.minecraft.item.crafting.ShapelessRecipes@66bbecd0
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeminetweaker.mc1102.recipes.ShapelessRecipeBasic@6bbcf946
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeminetweaker.mc1102.recipes.ShapelessRecipeBasic@2881715c
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeminetweaker.mc1102.recipes.ShapelessRecipeBasic@3aa874e2
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeminetweaker.mc1102.recipes.ShapelessRecipeBasic@3d9acd17
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeminetweaker.mc1102.recipes.ShapelessRecipeBasic@64f378d0
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeminetweaker.mc1102.recipes.ShapelessRecipeBasic@3f44809
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeminetweaker.mc1102.recipes.ShapedRecipeOre@4909a1c1
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeslimeknights.tconstruct.plugin.jei.CastingRecipeWrapper@7ae40add
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeslimeknights.tconstruct.plugin.jei.CastingRecipeWrapper@4bebcbc6
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeslimeknights.tconstruct.plugin.jei.CastingRecipeWrapper@5218a470
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeslimeknights.tconstruct.plugin.jei.CastingRecipeWrapper@152b067f
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeslimeknights.tconstruct.plugin.jei.CastingRecipeWrapper@660ae680
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeslimeknights.tconstruct.plugin.jei.CastingRecipeWrapper@1791cf6a
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeslimeknights.tconstruct.plugin.jei.CastingRecipeWrapper@5ad3a4fe
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeslimeknights.tconstruct.plugin.jei.CastingRecipeWrapper@46a6be80
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeslimeknights.tconstruct.plugin.jei.CastingRecipeWrapper@71a01949
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeslimeknights.tconstruct.plugin.jei.CastingRecipeWrapper@7ab6e721
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeslimeknights.tconstruct.plugin.jei.CastingRecipeWrapper@23f7f3d1
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeslimeknights.tconstruct.plugin.jei.CastingRecipeWrapper@2b6a0f5
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeslimeknights.tconstruct.plugin.jei.CastingRecipeWrapper@747ffc52
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeslimeknights.tconstruct.plugin.jei.CastingRecipeWrapper@18d82816
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeslimeknights.tconstruct.plugin.jei.CastingRecipeWrapper@543ebbc1
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeslimeknights.tconstruct.plugin.jei.CastingRecipeWrapper@7891c5c5
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeslimeknights.tconstruct.plugin.jei.CastingRecipeWrapper@24e90443
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeslimeknights.tconstruct.plugin.jei.CastingRecipeWrapper@45f12b63
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeslimeknights.tconstruct.plugin.jei.CastingRecipeWrapper@2a10c274
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeslimeknights.tconstruct.plugin.jei.CastingRecipeWrapper@212fb17a
09.05 08:53:24 [Server] Server thread/INFO [STDOUT]: [minetweaker.api.compat.DummyJEIRecipeRegistry:removeRecipe:14]: Removing Recipeslimeknights.tconstruct.plugin.jei.CastingRecipeWrapper@3b8b4e50
09.05 08:53:24 [Server] Server thread/INFO [FML]: Holder lookups applied
09.05 08:53:24 [Server] Server thread/INFO [FML]: Applying holder lookups
09.05 08:53:24 [Server] Server thread/ERROR [modtweaker]: Skipping event FMLModIdMappingEvent and marking errored mod modtweaker since required dependency MineTweaker3 has errored
09.05 08:53:24 [Server] Server thread/ERROR [loottweaker]: Skipping event FMLModIdMappingEvent and marking errored mod loottweaker since required dependency MineTweaker3 has errored
09.05 08:53:24 [Server] Server thread/ERROR [initialinventory]: Skipping event FMLModIdMappingEvent and marking errored mod initialinventory since required dependency MineTweaker3 has errored
09.05 08:53:23 [Server] Server thread/INFO [FML]: Unloading dimension -9999
09.05 08:53:23 [Server] Server thread/INFO [FML]: Unloading dimension -11325
09.05 08:53:23 [Server] Server thread/INFO [FML]: Unloading dimension 1
09.05 08:53:23 [Server] Server thread/INFO [FML]: Unloading dimension -1
09.05 08:53:23 [Server] Server thread/INFO [FML]: Unloading dimension 0
09.05 08:53:23 [Server] Server thread/INFO [OTG]: Unloading world "Biome Bundle"...
09.05 08:53:23 [Server] Server thread/INFO [Actually Additions]: Unloading WorldData for world -9999!
09.05 08:53:23 [Server] Server thread/INFO [OTG]: Unloading world "Biome Bundle"...
09.05 08:53:23 [Server] Server thread/INFO [Actually Additions]: Unloading WorldData for world -11325!
09.05 08:53:23 [Server] Server thread/INFO [Actually Additions]: Unloading WorldData for world 1!
09.05 08:53:23 [Server] Server thread/INFO [Actually Additions]: Unloading WorldData for world -1!
09.05 08:53:23 [Server] Server thread/INFO [OTG]: Unloading world "Biome Bundle"...
09.05 08:53:23 [Server] Server thread/INFO [Actually Additions]: Unloading WorldData for world 0!
09.05 08:53:23 [Server] Server thread/INFO Saving chunks for level 'Biome Bundle'/ExtraUtils2_Quarry_Dim
09.05 08:53:23 [Server] Server thread/INFO Saving chunks for level 'Biome Bundle'/Deep Dark
09.05 08:53:23 [Server] Server thread/INFO Saving chunks for level 'Biome Bundle'/The End
09.05 08:53:23 [Server] Server thread/INFO Saving chunks for level 'Biome Bundle'/Nether
09.05 08:53:22 [Multicraft] Skipped 163 lines due to rate limit (30/s)
09.05 08:53:21 [Server] INFO at minetweaker.mc1102.MineTweakerMod.onServerStarting(MineTweakerMod.java:171) ~[MineTweakerMod.class:?]
09.05 08:53:21 [Server] INFO at minetweaker.MineTweakerImplementationAPI.onServerStart(MineTweakerImplementationAPI.java:411) ~[MineTweakerImplementationAPI.class:?]
09.05 08:53:21 [Server] INFO at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:513) ~[MineTweakerImplementationAPI.class:?]
09.05 08:53:21 [Server] INFO at minetweaker.util.EventList.publish(EventList.java:49) ~[EventList.class:?]
09.05 08:53:21 [Server] INFO at leviathan143.loottweaker.common.tweakers.loot.LootTableTweaker$2.handle(LootTableTweaker.java:76) ~[LootTableTweaker$2.class:?]
09.05 08:53:21 [Server] INFO at leviathan143.loottweaker.common.tweakers.loot.LootTableTweaker$2.handle(LootTableTweaker.java:86) ~[LootTableTweaker$2.class:?]
09.05 08:53:21 [Server] INFO at net.minecraft.world.storage.loot.LootTableManager.func_186522_a(LootTableManager.java:48) ~[bas.class:?]
09.05 08:53:21 [Server] INFO at net.minecraft.world.storage.loot.LootTableManager.func_186521_a(LootTableManager.java:39) ~[bas.class:?]
09.05 08:53:21 [Server] INFO at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) ~[minecraft_server.1.10.2.jar:?]
09.05 08:53:21 [Server] INFO at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) ~[minecraft_server.1.10.2.jar:?]
09.05 08:53:21 [Server] INFO at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) ~[minecraft_server.1.10.2.jar:?]
09.05 08:53:21 [Server] INFO at com.google.common.cache.LocalCache.get(LocalCache.java:3934) ~[minecraft_server.1.10.2.jar:?]
09.05 08:53:21 [Server] INFO at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201) ~[minecraft_server.1.10.2.jar:?]
09.05 08:53:21 [Server] INFO com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Attempted to add a duplicate pool to loot table: main
09.05 08:53:21 [Server] Server thread/ERROR [FML]: Caught exception from MineTweaker 3 (MineTweaker3)
09.05 08:53:21 [Server] Server thread/ERROR [FML]: The following problems were captured during this phase
09.05 08:53:21 [Server] INFO UCHIJAAA	unidict{1.10.2-2.8} [UniDict] (UniDict-1.10.2-2.8.jar) 
09.05 08:53:21 [Server] INFO UCHIJAAA	moofluids{1.10.2-1.7.02.12b} [Moo Fluids] (MooFluids-1.10.2-1.7.02.12b.jar) 
09.05 08:53:21 [Server] INFO UCHIJAAA	xprings{1.3.0} [Experience Rings] (xprings-1.10-1.3.0.jar) 
09.05 08:53:21 [Server] INFO UCHIJAAA	xpplus{1.0} [XP-Plus] (xpplus-1.02.jar)

**Comment by Blue64** [comment]
A checklist of things to go over for bug Reports:
`>>` [Here](https://github.com/Blue64/Misc/issues/3) `<<`

GitHub Formatting Tips:
`>>` [Here](https://github.com/Blue64/Misc/issues/2) `<<`
