### ISSUE TITLE
Thermal Expansion Redstone Furnace smelting Rotarycraft flakes problem

### ISSUE THREAD

**Issue by AlpacaQueen4180** [stanhebben/MineTweaker3#469]
I added Rotarycraft and Reactorcraft to the modpack I'm playing (Divine Journey), I changed the output from Rotarycraft's own ingots (and items) to thermal expansion ones (or ones from their original mods). Everything was working until I tried putting pulverized iron into the Redstone Furnace, and found out that Redstone Furnace isn't smelting normal stuff like cobble, clay, Sandy Glass from xu, and all of the ores and dusts. Only thing that's working are the flakes, clusters from Thaumcraft, dense ores to normal ores, and some other misc stuffs.
While troubleshooting I found this message in the minetweaker log:

```
ERROR: Error executing Rotarycraft.zs: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =class cofh.thermalexpansion.util.crafting.FurnaceManager$ComparableItemStackFurnace id= 418303786 hashCode= 446628179 toString= cofh.thermalexpansion.util.crafting.FurnaceManager$ComparableItemStackFurnace@418303786{m:339, i:Reika.RotaryCraft.Items.ItemModOre@1046786880, v:6815}; object #2 =class cofh.thermalexpansion.util.crafting.FurnaceManager$ComparableItemStackFurnace id= 1711711052 hashCode= 446628179 toString= cofh.thermalexpansion.util.crafting.FurnaceManager$ComparableItemStackFurnace@1711711052{m:339, i:Reika.RotaryCraft.Items.ItemModOre@1046786880, v:6815}

hashCode() and/or equals() have inconsistent implementation
Key set lost entries, now got 354 instead of 399. This can manifest itself as an apparent duplicate key.
java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =class cofh.thermalexpansion.util.crafting.FurnaceManager$ComparableItemStackFurnace id= 418303786 hashCode= 446628179 toString= cofh.thermalexpansion.util.crafting.FurnaceManager$ComparableItemStackFurnace@418303786{m:339, i:Reika.RotaryCraft.Items.ItemModOre@1046786880, v:6815}; object #2 =class cofh.thermalexpansion.util.crafting.FurnaceManager$ComparableItemStackFurnace id= 1711711052 hashCode= 446628179 toString= cofh.thermalexpansion.util.crafting.FurnaceManager$ComparableItemStackFurnace@1711711052{m:339, i:Reika.RotaryCraft.Items.ItemModOre@1046786880, v:6815}

hashCode() and/or equals() have inconsistent implementation
Key set lost entries, now got 354 instead of 399. This can manifest itself as an apparent duplicate key.
	at gnu.trove.impl.hash.TObjectHash.buildObjectContractViolation(TObjectHash.java:464)
	at gnu.trove.impl.hash.TObjectHash.throwObjectContractViolation(TObjectHash.java:448)
	at gnu.trove.map.hash.THashMap.rehash(THashMap.java:403)
	at gnu.trove.impl.hash.THash.postInsertHook(THash.java:388)
	at gnu.trove.map.hash.THashMap.doPut(THashMap.java:178)
	at gnu.trove.map.hash.THashMap.put(THashMap.java:145)
	at cofh.thermalexpansion.util.crafting.FurnaceManager.addRecipe(FurnaceManager.java:225)
	at modtweaker2.mods.thermalexpansion.handlers.Furnace$Add.apply(Furnace.java:60)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:70)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:169)
	at modtweaker2.mods.thermalexpansion.handlers.Furnace.addRecipe(Furnace.java:46)
	at Rotarycraft.__script__(Rotarycraft.zs:384)
	at __ZenMain__.run(Rotarycraft.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:163)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:656)
	at ftb.ReloadHandler.onReloaded(ReloadHandler.java:42)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_331_ReloadHandler_onReloaded_EventFTBReload.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at ftb.lib.api.EventLM.post(EventLM.java:9)
	at ftb.lib.FTBLib.reload(FTBLib.java:85)
	at ftb.lib.mod.FTBLibEventHandler.onWorldLoaded(FTBLibEventHandler.java:39)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_330_FTBLibEventHandler_onWorldLoaded_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:230)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:258)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

And here's the zs file I used: https://gist.github.com/AlpacaQueen4180/0a9ef906fa6cffd1c98747287ffd4906

**Comment by VariableVixen** [comment]
First, please pastebin your logs or at _least_ wrap them in code blocks. Second, this bit suggests that it's in either Thermal Expansion (the objects being compared) or in RotaryCraft (the _items_ being compared) rather than in MT:

`
Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode(). See bullet point two in that method's documentation. object #1 =class cofh.thermalexpansion.util.crafting.FurnaceManager$ComparableItemStackFurnace id= 418303786 hashCode= 446628179 toString= cofh.thermalexpansion.util.crafting.FurnaceManager$ComparableItemStackFurnace@418303786{m:339, i:Reika.RotaryCraft.Items.ItemModOre@1046786880, v:6815}; object #2 =class cofh.thermalexpansion.util.crafting.FurnaceManager$ComparableItemStackFurnace id= 1711711052 hashCode= 446628179 toString= cofh.thermalexpansion.util.crafting.FurnaceManager$ComparableItemStackFurnace@1711711052{m:339, i:Reika.RotaryCraft.Items.ItemModOre@1046786880, v:6815}
`

**Comment by AlpacaQueen4180** [comment]
Sorry, it's my first time using github.
Since it showed up in the Minetweaker log I thought it would be related to MT. I guess I'll go ask it on Reddit or Reika's issue page. Thanks.
