### ISSUE TITLE
Calling a script "test.zs" does not work.

### ISSUE THREAD

**Issue by Belgabor** [stanhebben/MineTweaker3#72]
If you call a script "test.zs" all hell breaks loose, nothing in it works. There are absolutely no useful error messages. Apparently this leads to some internal snafu, maybe it's some kind of name collision.

Please either make it work or error out on the name, this has cost me a lot of "wtf am I doing wrong?!?" time...

    [17:26:05] [Server thread/ERROR]: Couldn't process command: 'mt reload'
    java.lang.NoSuchMethodError: Test.__script__()V
	at __ZenMain__.run(test.zs) ~[?:?]
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:158) ~[MTTweaker.class:?]
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:561) ~[MineTweakerImplementationAPI.class:?]
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:78) ~[MineTweakerImplementationAPI$1.class:?]
	at minetweaker.MineTweakerImplementationAPI$18.execute(MineTweakerImplementationAPI.java:547) ~[MineTweakerImplementationAPI$18.class:?]
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124) ~[MCServer$MCCommand.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:734) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:713) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
    [17:26:05] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command
    [17:26:50] [Client thread/INFO]: [CHAT] Scripts reloaded

**Comment by jaredlll08** [comment]
I specifically use test.zs when I test. pretty sure this can be closed.
