### ISSUE TITLE
Error with Command /minetweaker Recipes

### ISSUE THREAD

**Issue by Dream-Master** [stanhebben/MineTweaker3#91]
[01:07:42] [Server thread/ERROR]: Couldn't process command: 'minetweaker recipes'
java.lang.NullPointerException
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217) ~[add.class:?]
    at minetweaker.mc1710.item.MCItemStack.toString(MCItemStack.java:338) ~[MCItemStack.class:?]
    at java.lang.String.valueOf(Unknown Source) ~[?:1.7.0_67]
    at java.lang.StringBuilder.append(Unknown Source) ~[?:1.7.0_67]
    at minetweaker.api.recipes.ShapedRecipe.toCommandString(ShapedRecipe.java:224) ~[ShapedRecipe.class:?]
    at minetweaker.MineTweakerImplementationAPI$6.execute(MineTweakerImplementationAPI.java:203) ~[MineTweakerImplementationAPI$6.class:?]
    at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610) ~[MineTweakerImplementationAPI$19.class:?]
    at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124) ~[MCServer$MCCommand.class:?]
    at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[01:07:42] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command

**Comment by boop5** [comment]
Have this problem with version MineTweaker3-1.7.10-3.0.10B

```
[14:35:07] [Client thread/INFO]: [CHAT] Generating recipe list, this could take a while...
[14:35:07] [Server thread/ERROR]: Couldn't process command: 'mt recipes'
java.lang.NullPointerException
[14:35:07] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command
```

**Comment by jaredlll08** [comment]
Give the game log and minetweaker.log please
